ISISComputingGroup/EPICS-ioc

INSTETC/INSTETC-IOC-01App/Db/inst_real_parameters.substitutions, INSTETC/INSTETC-IOC-01App/Db/inst_real_parameters.template, INSTETC/INSTETC-IOC-01App/Db/inst_string_parameters.substitutions, INSTETC/INSTETC-IOC-01App/Db/inst_string_parameters.template, INSTETC/INSTETC-IOC-01App/Db/user_parameters.template
This is part of ISISComputingGroup/IBEX#1133 and needs to be merged together with corresponding branch in inst_servers
To test: check 
caget -S -t %MYPVPREFIX%CS:BLOCKSERVER:SAMPLE_PARS
should return a sensible list like
["PARS:SAMPLE:AOI", "PARS:SAMPLE:GEOMETRY", "PARS:SAMPLE:HEIGHT", "PARS:
AME", "PARS:SAMPLE:PHI", "PARS:SAMPLE:THICK", "PARS:SAMPLE:TYPE", "PARS:SAMPLE:WIDTH", "PARS:SCRIPT:NAME"]
=> Set PVCATEGORY to an appropriate value

TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/st-common.cmd, TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/st-psu.cmd, TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/st.cmd, TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-02/st.cmd, TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-03/st.cmd, TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-04/st.cmd
Corrections to the st.cmd set-ups so that the IOC will run.
To test:
Via the console app, any of these should load, but unless the macros/global changes mentioned below have been made there should be no records beyond the standard ones
The easiest method if to alter your globals.txt, although any of these macros can be set via the configurations.
In the file C:\Instrument\Settings\config\#######\globals.txt, where ####### is the server you are testing on, add the following as an example (if you have a PSU available use those settings) as part of the IOC specific macros:
GENESYS_01__PORT1=COM10
GENESYS_01__ADDR1=10
GENESYS_02__PORT1=COM11
GENESYS_02__ADDR1=10
GENESYS_02__PORT3=COM12
GENESYS_02__ADDR3=10
Starting the IOC GENESYS_01 will likely lead to a lot of errors, but should relate to …
=> Run up to 10 PSUs in each IOC

SDTEST/sdtest_docs/sdtest.rst
Explicitly mark some hyperlinks as anonymous, but probably only needed to escape the trailing __
To test, check that running    isisdoc\make_manual.bat     gives no errors
=> Escape __ as looks like anonymous hyperlink to rst

Makefile
ISISComputingGroup/IBEX/issues/1271
=> Ticket 1271: no longer tries to build Mk3Chopper for non-vs2010

AG3631A/iocBoot/iocAG3631A-IOC-01/st.cmd, DELFTBPMAG/iocBoot/iocDELFTBPMAG-IOC-01/st.cmd, DELFTBPMAG/iocBoot/iocDELFTBPMAG-IOC-02/st.cmd, EUROTHERM/iocBoot/iocEUROTHERM-IOC-01/st.cmd, EUROTHERM/iocBoot/iocEUROTHERM-IOC-02/st.cmd, HAMEG8123/iocBoot/iocHAMEG8123-IOC-01/st.cmd, HAMEG8123/iocBoot/iocHAMEG8123-IOC-02/st.cmd, JULABO/iocBoot/iocJULABO-IOC-01/st.cmd, JULABO/iocBoot/iocJULABO-IOC-02/st.cmd, KEPCO/iocBoot/iocKEPCO-IOC-01/st.cmd, KEPCO/iocBoot/iocKEPCO-IOC-02/st.cmd, LAKESHORE218/iocBoot/iocLakeshore218-IOC-01/st.cmd, LAKESHORE218/iocBoot/iocLakeshore218-IOC-02/st.cmd, SPINFLIPPER306015/iocBoot/iocSPINFLIPPER-IOC-01/st.cmd, TEKDMM40X0/iocBoot/iocTEKDMM4040-IOC-01/st.cmd, TPG300/iocBoot/iocTPG300-IOC-01/st.cmd, TPG300/iocBoot/iocTPG300-IOC-02/st.cmd, TPG300/iocBoot/iocTPG300-IOC-03/st.cmd, TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/st.cmd, TTIEX355P/iocBoot/iocTTIEX355P-IOC-02/st.cmd
All COM ports are now available as Macros, for LARMOR these macros have been added to globals.txt so that no change at all should be seen.
Without hardware there is no way to test this, but this system of macros has been used and is tested.
Have standardised to PORT as the macro name, as it is not that hard to change when we have decided on final names, and at least if they are standard, and the majority of values being set externally were already using PORT.
Have also deleted anywhere where a COM value is set in an st.cmd, whether it was commented out or not, just for clarity.
=> Ticket1220 macro for com ports

FINS/FINS-IOC-01App/Db/Makefile, FINS/FINS-IOC-01App/Db/imat-attn.substitutions, FINS/FINS-IOC-01App/Db/imat-attn.template
Relates to https://github.com/ISISComputingGroup/IBEX/issues/979
Without access to the PLC, this can only be tested that the db file is created from the template and substitutions.
It may be possible to test this with the IOC, in which case an appropriate st.cmd will need to be created within the settings/configurations directory loading the imat-attn.db, and the appropriate IP address would need to be added as a macro somewhere (I recommend globals.txt). For that IP address, either contact Gareth/Kathryn for the information, or look at IMAT.
When testing it, merely monitor the OPEN and CLOSED PVs, and set the OPEN:SP and CLOSED:SP to open and close the attenuator as expected.
=> Ticket979 imat attenuator

DFKPS/DFKPS-IOC-01App/Db/DFKPS.db
Relates to https://github.com/ISISComputingGroup/IBEX/issues/1313
There was a need for a block that meant and alias was required for the SETIRAW PV, this was done and tested on the fly on LARMOR, this is already on the live system so doesn't need to be tested.
=> Capture change to ensure LARMOR can be updated

GALIL/GALIL-IOC-01App/src/build.mak, GALIL/iocBoot/iocGALIL-IOC-01/barndoors.cmd, GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
Muon front end barn doors. See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Barndoors-and-Momentum-Slits-on-MUON-Front-End for description.
Other pull requests:
https://github.com/ISISComputingGroup/EPICS-barndoors/pull/1
https://github.com/ISISComputingGroup/ibex_gui/pull/287
https://github.com/ISISComputingGroup/EPICS/pull/31
https://github.com/ISISComputingGroup/IBEX/issues/1388
1. Create the Gallil settings for the Muon front end (see release notes).
1. User can start a Galili_01 and it will start the barndoors and momentum slits records (if configured).
1. User can see a muon front end on a synoptic
1. Test gap for barndoors and momentum slits above the minimum (for barndoors) when set set motors to correct position as per calibration table (at end)
1. Given …
=> Add support for barndoors

MK3CHOPPER/MK3CHOPPER-IOC-01App/src/mk3Driver.cpp
ISISComputingGroup/IBEX/issues/1360
Stay on master, open the st.cmd and change 0 to 1 in the following line to put into sim mode:
mk3DriverConfigure("MK3", "C:/MK3_Chopper.config", `1`)
start the IOC
caget %MYPVPREFIX%MK3CHOPPER_01:CH1:PHAS:SP
This probably will return 10 (I don't know why! Something to do with asyn holding a value from a different read?)
Change to this branch and rebuild then repeat the previous steps. The caget should return 100 (because that is what the simulator sets it to)
=> Ticket #1360: Small change to read PHASE SP

ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd
https://github.com/ISISComputingGroup/IBEX/issues/1274
Added  macros for Time Channel Boundaries file paths, naming pattern etc. to ISISDAE IOC.
TCB files live in `Instrument/Settings//config/[Instrument Name]/configurations/tcb` and contain "tcb" in their filename.
=> Ticket1274 time channel settings in dae tab (IOC)

Makefile
Use explicit directory list for IOC names
ISISComputingGroup/IBEX#1485
IOC directory builds without error
---
=> Use explicit directory list

DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
Fixed description of "CALIBRATED" macro in DFKPS IOC
https://github.com/ISISComputingGroup/IBEX/issues/1475
Correct macro descriptions for DFKPS IOCs are displayed in IBEX.
---
=> fixed macro description

MK3CHOPPER/MK3CHOPPER-IOC-01App/src/mk3Driver.cpp, MK3CHOPPER/MK3CHOPPER-IOC-01App/src/mk3Driver.h, MK3CHOPPER/iocBoot/iocMk3CHOPPER-IOC-01/st.cmd
https://github.com/ISISComputingGroup/IBEX/issues/1314
The Mk3Chopper knows how many choppers it has, so if we get that value first then we can only load the records for the choppers present.
As part of the IOC starting up it creates macros for each chopper that is present.
If the macro is defined then the records are loaded for that chopper.
* Update the MK3CHOPPER folder in this repo.
* Type 'make' in this directory
* Move to iocBoot\iocMk3CHOPPER-IOC-01
* Open the st.cmd and **change it to use a mock chopper**
```
mk3DriverConfigure("MK3", "C:/LabVIEW Modules/Drivers/ISIS MK3 Disc Chopper/MK3_Chopper.config", 1)
```
* Run the IOC (runIOC.bat st.cmd)
* Check the IOC messages to see the following text.
```
dbLoadRecords("db/mk3.db","P=IBEX_MATT:MJC23:MK3CHOPPER_01:, Q=CH1:, PORT=MK3, …
```
=> Ticket #1314: Mk3Chopper will automatically adjust to the number of choppers found on startup

LINKAM95/LINKAM95-IOC-01App/Db/LINKAM95.db
The Linkam95 device expects the T command to always come first. Previously a Pa0 was sent initially that would subsequently be ignored. The Linkam95 DB file has been updated to ensure that the T command comes first with 1 subsequent Pa0 afterwards.
Note that I've created a simple device emulator for the Linkam that will help with this ticket:
https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/3
https://github.com/ISISComputingGroup/IBEX/issues/1509
- T command sent first when IOC started
- Pa0 is sent after the first T command
- Subsequent T commands are not followed by a Pa0
---
=> Ticket1509: First Linkam command must be "T"

MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml
The Iris sample changer needs to support STOP_BITS=10 and negative upper/lower limits
https://github.com/ISISComputingGroup/IBEX/issues/1584
As above
---
=> Change McLennan macro patterns to accept values as found on Iris

MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
Change the name associated with motor sims for McLennan motors so that if I use multiple motors on the same IOC, it will launch correctly. Previously the launch aborted almost straight away.
https://github.com/ISISComputingGroup/IBEX/issues/1546
Can launch multiple simulated motors on the same McLennan IOC. These macros may be helpful:
```
SIMULATE=1
MCLEN_01__MTRCTRL=1
MCLEN_01__PORT1=COM1
MCLEN_01__PORT2=COM1
```
---
=> IOC: Cannot have multiple simulated motors attached to single MCLEN IOC

EUROTHERM/EUROTHERM-IOC-01App/Db/devEurotherm.db
If the raw (as in steam device string) setpoint and readback
differ by more than $(P)SP:CHKTOL then a request is made to
reissue the setpoint up to $(P)SP:NRETRY times at 1 second intervals. 
See ISISComputingGroup/IBEX#1703
To test, you could set  $(P)SP:CHKTOL to  -1  with a CAPUT and
then the next setpoint sent should automatically get resent every second NRETRY times to 
the hardware. While retrying,  $(P)_CHECKSP  should have the value of 1 and also be in a MINOR alarm state.
To check for missed setpoints, maybe write a genie-python script to send setpoints in a loop to the  hardware with the default .001 tolerance and have a camonitor on  $(P)_CHECKSP to see if any get lost and are picked up. Don't send setpoints too fast, say every few seconds. If you send them too fast they could …
=> Check and resend eurotherm setpoint

EUROTHERM/EUROTHERM-IOC-01App/Db/devEurotherm.db
Commented out SCAN field of OUT_SP, as per ISISComputingGroup/IBEX#1630
ISISComputingGroup/IBEX#1709
Setpoint does NOT get sent at startup.
This was already tested as part of ISISComputingGroup/IBEX#1630 and is currently in as a hotfix on IRIS
---
=> Ticket 1709: commented out SCAN field of SP_OUT

MCLEN/MCLEN-IOC-01App/src/build.mak, MCLEN/iocBoot/iocMCLEN-IOC-01/axes.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml, MCLEN/iocBoot/iocMCLEN-IOC-01/motionsetpoints.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/sampleChanger.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd
- McLennan to call routines to initialize the sampleChanger
- Encoder ratio can be negative
https://github.com/ISISComputingGroup/IBEX/issues/1708
- Can run a sample changer/linear sample changer using a McLennan motor
- Can set the encoder ratio of a McLennan to be negative
---
=> Ticket1708 iris mclennan

CRYVALVE/CRYVALVE-IOC-01App/Db/CRYVALVE.db, CRYVALVE/iocBoot/iocCRYVALVE-IOC-01/st.cmd, CRYVALVE/iocBoot/iocCRYVALVE-IOC-02/st.cmd
Create aliases for some of the Cryovalve PVs so they work with cset. Cset assumes PVs of the form `[PV]`, `[PV]:SP` so that when `cset([PV],value)` is called, it really sets the value on `[PV]:SP`. The old form of the cryvalve IOC didn't allow that.
The new db structure has a `STATUS:SP` PV so it works with the existing status PV. I've also created the pair `STAT` and `STAT:SP` in line with PV naming standards. I've left the old PVs in place to preserve backwards compatibility. 
I only updated the Cryovalve IOC. I looked at the others listed in the ticket and didn't identify any further changes that were necessary.
https://github.com/ISISComputingGroup/IBEX/issues/1663
---
=> Add aliases for CV status

ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd
Add run control flushing to begin() (part of larger ticket)
Put a Monitor on %MYPVPREFIX%CS:RC:SYNC:SP before a begin()
See ISISComputingGroup/IBEX#1735
---
=> Adjust startup for new isisdae.db

EUROTHERM/EUROTHERM-IOC-01App/Db/devEurotherm.db
Mark CHECKSP as defined on startup to avoid "undefined" alarm being raised
See ISISComputingGroup/IBEX#1733
Start eurothem ioc and check that no alarms are raised
above is true
---
=> Mark as defined on startup to avoid alarm trigger

LKSH336/LKSH336-IOC-01App/Db/lakeshore336.substitutions, LKSH336/iocBoot/iocLKSH336-IOC-01/st-common.cmd
Added a DISABLE macro, for consistency with other IOCs
It doesn't fix any ticket, but it was done as part of ISISComputingGroup/IBEX#1692
The IOC still boots fine
---
=> Added a disable macro

MCLEN/MCLEN-IOC-01App/src/build.mak, MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
McLennan connects to the new homing sequencer at startup. Requires corresponding change in motorApp
https://github.com/ISISComputingGroup/IBEX/issues/1725
McLennan IOC homing behaviour is as expected:
The behaviour should effectively be the same as before. What is important that it is the view of the reviewer that the infrastructure is in place so that we can define custom behaviour easily in future. Note that are several things that aren't explicit in the current implementation:
- The homing mode is sent from the IOC to the sequencer at startup, but it is never used because we only have one mode
- The homing mechanism works by setting PV values in the McLennan motor, not by talking to the motor directly (much easier). Constant velocity homing is easy because we can simply call the JOG …
=> Ticket1725 custom mc lennan homing routines

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
Assign MOVING PVs to the NOTRAPW access security group so they are not reported by CAPutLog
See ISISComputingGroup/IBEX#1847
Before merge, you should see MOVING.A etc info log messages as described in ticket above whenever a motor moves. After merge you should see no such messages when a motor moves. 
---
=> Do not record writes to MOVING PV

JULABO/iocBoot/iocJULABO-IOC-01/st-common.cmd, JULABO/iocBoot/iocJULABO-IOC-01/st.cmd, JULABO/iocBoot/iocJULABO-IOC-02/st.cmd, LKSH336/iocBoot/iocLKSH336-IOC-01/st-common.cmd
https://github.com/ISISComputingGroup/IBEX/issues/1530
Freddie added support for IOCs to find a free port for Lewis (née Plankton). This PR adds it to the JULABO IOCs as an example of how to use it.
If you put the JULABO into DEVSIM then it should find a free port which could be used for Lewis. You can see this by looking through the IOCs output on start up.
It will complain about there being nothing on that port as Lewis won't be running, but that is a story for another day.
In DEVSIM mode,  the JULABO will find a free port.
---
=> Added freeport finder to julabo IOCs

MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml
Changed the macro description for velocities. The length units for McLennans is determined by MSTP/MRES to define the conversion between motor pulses to distance.
https://github.com/ISISComputingGroup/IBEX/issues/2044
---
=> Velocity is in units of units/s, defined by MSTP/MRES

TPG300/iocBoot/iocTPG300-IOC-02/st.cmd, TPG300/iocBoot/iocTPG300-IOC-03/st.cmd
The TPG300 IOCs didn't start. With this patch, they should start successfully.
https://github.com/ISISComputingGroup/IBEX/issues/2063
All three TPG300 IOCs start successfully.
---
=> Ticket2063 fix tpg300 ioc

ISISDAE/ISISDAE-IOC-01App/src/build.mak, ISISDAE/configure/CONFIG_SITE, ISISDAE/configure/RELEASE
Reference, but not call, areaDetector framework in preparation for ZOOM work 
See ISISComputingGroup/IBEX#2100
Everything still builds
---
=> Link areaDetector into DAE

SCIMAG3D/iocBoot/iocSCIMAG3D-IOC-01/config.xml, SCIMAG3D/iocBoot/iocSCIMAG3D-IOC-01/st.cmd
Allow the instrument scientist to set the LVDcom options and host.
https://github.com/ISISComputingGroup/IBEX/issues/1979
* Without a setting vi should not start but a warning message should be written in IOC which says `"C:\LabVIEW Modules\Drivers\Scientific Instruments\3D Magnet\Source Code\Vector-
control-v16isis.vi" is not running on localhost and autostart is disabled`. 
* With setting it should do what setting suggests.
---
=> Add LVDCOM macros to allow settings for Labview Start

KHLY2400/KHLY2400-IOC-01App/Db/KHLY2400.db
I've separated out the "general" PVs into separate read/write controls. They do the same thing but allow us to have two independent controls on the OPI as in the VI.
GUI PR is here: https://github.com/ISISComputingGroup/ibex_gui/pull/465
https://github.com/ISISComputingGroup/IBEX/issues/2045
Note that it is perfectly possible to put set commands in the read PV and get commands in write. You'll just get too much/too little output respectively.
---
=> Ticket2045 Keithley general read/write separated

LINMOT/LINMOT-IOC-01App/Db/motor.substitutions, LINMOT/LINMOT-IOC-01App/Db/motorSim.substitutions, LINMOT/iocBoot/iocLINMOT-IOC-01/config.xml, LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd, LINMOT/iocBoot/iocLINMOT-IOC-01/st-motor.cmd, MCLEN/MCLEN-IOC-01App/Db/motor.substitutions, MCLEN/MCLEN-IOC-01App/Db/motorSim.substitutions, MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml, MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
There were a few errors in the initial LinMot. The offsets and motor resolution weren't being propagated to the motor.
It is helpful to know that the motor reports its position in steps so the position given to the user is:
```
position = resolution*motor_position + offset
```
This can be used to confirm that the reported position is correct as the offset and resolution are varied. Assume you have a configuration where:
```
r_old : old resolution
r_new : new resolution
o_old : old offset
o_new : new offset
p_old : old position
p_new : new position
```
When the configuration is changed from the old to the new macros then the new position should be:
```
p_new = r_new*(p_old - o_old)/r_old + o_new
```
https://github.com/ISISComputingGroup/IBEX/issues/2219
- Speed should increase linearly …
=> Ticket2219 hrpd jaws commissioning

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Adds autotune as an "interesting" field (useful because Polaris has a block looking at autotune)
https://github.com/ISISComputingGroup/IBEX/issues/2221
---
=> Ticket2221 make autotune interesting

LINMOT/iocBoot/iocLINMOT-IOC-01/config.xml, LINMOT/iocBoot/iocLINMOT-IOC-01/st-motor.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml, MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
I've added the `NAMEn` macros for LinMots and McLennans so they can have a custom, recognisable name
https://github.com/ISISComputingGroup/IBEX/issues/2290
- Add a McLennan IOC to a configuration (set in DEVSIM mode)
- Give the IOC a `NAMEn` macro for an active axis
- Verify the name appears in the Name panel of the motor OPI
- Do the same for LinMots
---
=> Ticket2290 add name macro for motors

ROTSC/ROTSC-IOC-01App/Db/HRPD_specific.db, ROTSC/ROTSC-IOC-01App/Db/error_calculator.db, ROTSC/ROTSC-IOC-01App/Db/rotating_sample_changer.db
I've added some missing description fields to the rotating sample changer PVs. I also changed 'CARROUSEL' to 'CAROUSEL', the former being the French spelling, the latter being the English. There is a corresponding PR for the GUI.
https://github.com/ISISComputingGroup/IBEX/issues/2412
---
=> Add some missing descriptions. Fix spelling of carousel

ROTSC/ROTSC-IOC-01App/Db/HRPD_specific.db, ROTSC/ROTSC-IOC-01App/Db/rotating_sample_changer.db
Update the rotating sample changer PVs to end with SP so that they don't throw errors when set using a block.
https://github.com/ISISComputingGroup/IBEX/issues/2314
---
=> Update PV names to have :SP records for settable values

DFKPS/DFKPS-IOC-01App/Db/DFKPS_8800_status.db
As per https://github.com/ISISComputingGroup/IBEX/issues/2592 the power PV for the Danfysik 8800 was being set to 1 when off and 0 when on. This wasn't normally an issue as the ONAM/ZNAM were also swapped. 
* Start DFKPS as a 8800 model and in recsim
* Open the muon front end opi
* Confirm that the power pv and LED on the OPI match
* caput %MYPVPREFIX%DFKPS_01:SIM:STATUS 2
* Confirm that power pv changes
* Confirm that the power pv and LED on the OPI match
---
=> Ticket 2592: Inverted the DFKPS power PV

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
This changes the eurotherm ramping units for K/s to K/min
This also brings the eurotherm under test.
- Check that you can run the device emulator
- Check that the tests pass
Other PRs:
Original issue is: https://github.com/ISISComputingGroup/IBEX/issues/2465
---
=> Eurotherm ramp rate units

FINS/FINS-IOC-01App/Db/zoom-vacuum-base.template, FINS/FINS-IOC-01App/Db/zoom-vacuum-commands.template
Altered the files so that they will generate a db file matching one created for a hotfix.
The main item is an addition of a longout that is forward linked to from certain items such as the monitor insert and extract records which in turn writes a value of 1, always 1, to the PLC
Relates to https://github.com/ISISComputingGroup/IBEX/issues/2665
To test, re-make the FINS IOC and check that appropriate records are created. If in doubt as to what those records should be either look at the db file on ZOOM, or ask Kathryn for a copy of it.
The interim records are in place so that ZOOM will be able to function should the system be upgraded.
---
=> Fixes to reproduce the working hotfix on ZOOM

KHLY2400/iocBoot/iocKHLY2400-IOC-01/config.xml, KHLY2400/iocBoot/iocKHLY2400-IOC-01/st-common.cmd
Makes the terminator on the Keithley 2400 configurable.
https://github.com/ISISComputingGroup/IBEX/issues/2695
Needs the PR at https://github.com/ISISComputingGroup/EPICS-Keithley2400/pull/1
Now modify the terminators in `C:\Instrument\Apps\EPICS\support\DeviceEmulator\master\lewis_emulators\keithley_2400\interfaces\stream_interface.py` to be `\r`.
Useful command to launch the emulator: `C:\Instrument\Apps\Python\python.exe C:\Instrument\Apps\Python\Scripts\lewis.exe -r 127.0.0.1:10000 -p stream -a C:\Instrument\Apps\EPICS\support\DeviceEmulator\master -k lewis_emulators keithley_2400 -p "stream: {bind_address: localhost, port: 57677}"`
---
- [Disable …
=> Put terminator in st-common.cmd.

KHLY2400/KHLY2400-IOC-01App/Db/KHLY2400.db, KHLY2400/iocBoot/iocKHLY2400-IOC-01/st-common.cmd
This PR fixes a crash in the ibex gui when the Keithley 2400 had a disconnected sensor.
The sequence of events that caused this crash was:
- Keithley gives a value of `10^38` if a sensor is disconnected
- This was propagated through the IOC
- The OPI graph widget choked when trying to plot such a large value.
I've modified the IOC so that any value above `10^20` is rejected and replaced with `Nan`, which also makes it go into an alarm state. This limit should be comfortably above any value which will realistically be measured, but is also able to be plotted by CSS.
https://github.com/ISISComputingGroup/IBEX/issues/2693
With a Keithley 2400 in recsim mode:
You can also test in devsim mode. This is a bit more fiddly to set up:
- Launch the emulator using …
=> Ticket2693 keithley crash

MK3CHOPR/MK3CHOPR-IOC-01App/src/mk3Driver.cpp, MK3CHOPR/iocBoot/iocMk3CHOPR-IOC-01/st.cmd
The current Mk3 chopper crashes on encountering error code 21. I've increased the buffer size in the IOC to cope with bigger messages. There's a corresponding change in the support module to make the copy safer.
I also edited the startup command to use the MockChopper in DevSim mode to avoid having to choose it manually.
https://github.com/ISISComputingGroup/IBEX/issues/2633
To get error messages emitted by the Mock Chopper, do the following:
- Change the error-code to something positive in MockChopper.cs. For instance `PutNominalPhaseErrorWindow`
- Change the error message in `ResolveErrorCode` in `MockChopper.cs`
- Build the chopper support module and IOC
- Run the IOC in DevSim mode which, with the IOC PR, will instruct it to use the mock chopper
- Perform the operation you set the …
=> Ticket2633 mk3 chopper speed crash

IEG/IEG-IOC-01App/Db/ieg.db
As per ticket:
- ~~Rename existing PVs from `PRESSURE` to `PRES` in line with IBEX standards~~
- My bad, `PRESSURE` is IBEX standard. Confusing because temperature is `TEMP`
- ~~Have a `PRES:RAW` PV with the true calculated value~~
- `PRESSURE:RAW` already exists. There are now 2 PVs, `PRESSURE:OUT` and `PRESSURE:CALC`. `PRESSURE:OUT` is limited to 0-350 mbar where as `PRESSURE:CALC` is the calculated pressure. I have aliased `PRESSURE` to `PRESSURE:OUT` so that if you want a block that just reports 0-350, you can use the vanilla `PRESSURE` PV.
- `PRES` to be limited to 0-350 mbar with suitable alarms
- `PRES` GUI to have a similar message to "> 350mbar" message for negative pressures
- Adjust labels on GUI
- Remove sample bin pressure from GUI ~~and IOC~~
- Sample bin pressure from …
=> Ticket2758 ieg negative pressure

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
When the Eurotherm temperature SP is changed, it should update the device SP:RBV even if the SP hasn't changed. This is most evident if the underlying calibration file has been changed.
The issue arises because using a FLNK on a record with I/O intr doesn't cause it to process. Forward linking directly to the PROC field via channel access avoids the issue
https://github.com/ISISComputingGroup/IBEX/issues/2683
- Set the temperature SP
- Change the calibration file, so that the SP:RBV changes
- Set the temperature SP again to the same value as it currently has
- The SP:RBV changes to match the SP
--- …
=> FLNK does not cause trigger on I/O intr record

GALIL/GALIL-IOC-01App/Db/galil_userdef_records8.substitutions
See https://github.com/ISISComputingGroup/IBEX/issues/2607. Added additional params as requested by motion control group
Confirm that the DB and DS parameters can be and read on a galil.
---
=> Ticket 2607: Added additional galil ceramic params

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Fixes syntax errors in eurotherm
https://github.com/ISISComputingGroup/IBEX/issues/2816
Eurotherm no longer errors
---
=> Fix eurotherm

MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd
I've added an argument to PM304Config so that, if set, it sends a reset command before every move. I haven't at the moment made it configurable via a macro because I don't think we will often want to override the default. If we do, perhaps it's the wrong solution.
https://github.com/ISISComputingGroup/IBEX/issues/2760
---
=> Ticket2760: Add config arg for resetting after each move

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Make max output interesting so it is easy to make it a block and so the users can set the max power.
https://github.com/ISISComputingGroup/IBEX/issues/2749
PV appears in list of medium interest PVs.
---
=> Make max output interesting so that it can be found in the list of pvs

MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st.cmd
I've set the default output debug level so that not all commands are written to the log. This is more typical of other motors. The current level also ensures that resets (that aren't ignored) do appear in the log where as other commands don't which make them easier to spot.
I've also reinstated the code that sets the motor to closed mode and sets the encoder ratio. I'm surprised its removal hasn't been spotted until now. It's removal seems to have been accidental given the commit history
https://github.com/ISISComputingGroup/IBEX/issues/2760
Notably with the reintroduction of the encoder ratio, if you set it to something like -1/1 (remember ERES**3** for the G39 motor) it can easily be put into a tracking abort move just by moving it with this setting.
---
- [PV …
=> Ticket2760 send mc lennan reset on move

SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-01/st-common.cmd
Modified st-common.cmd to include option for IOC to run in simulation mode.  However, this is currently incompatible with Asyn.
https://github.com/ISISComputingGroup/IBEX/issues/2567
---
=> Added simulation support to no avail

MERCURY_ITC/MERCURY-IOC-01App/Db/Makefile, MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml, MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st.cmd
Add PVs for Mercury iTC gas levels
https://github.com/ISISComputingGroup/IBEX/issues/2840
- PVs exist that match those in the GEM configs
- [Mercury blocks.txt](https://github.com/ISISComputingGroup/EPICS-ioc/files/1647224/Mercury.blocks.txt)
- IOC communicates effectively with the OPI
---
=> Add separate level logic

GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
See https://github.com/ISISComputingGroup/IBEX/issues/2831
---
=> Ticket2831: Galil checks for incorrectly specified macro before autosaving

MK3CHOPR/MK3CHOPR-IOC-01App/src/mk3Driver.cpp
Reinitialize the chopper under more conditions.
This fixes a bug that was seen on IRIS where, if the `initialize()` call fails once after a .NET timeout, the IOC will never try to reconnect again.
Similar issues appear to have occurred in the past on other beamlines, see for example `hrpd\Instrument\var\logs\ioc\MK3CHOPR_01-20171120.log` (I don't think they reported that to us at the time) so this is not a new/recent failure.
I'm not sure how we can test this without a chopper as it needs to be connected to an actual chopper to cause the error.
https://github.com/ISISComputingGroup/IBEX/issues/2943
---
- [Disable records](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Disable-reco …
=> More general error handling

FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db
Uses a single command to send delay setpoint
https://github.com/ISISComputingGroup/IBEX/issues/2951
---
=> Modify db to use new protocol syntax

AG3631A/AG3631A-IOC-01App/Db/devagilent3631A.db, AG3631A/iocBoot/iocAG3631A-IOC-01/st.cmd
Make IOC AG3631A work with RecSim. Fix syntax error in Db
IOC Tests Run
IOC Tests Run
---
=> Make IOC AG3631A work with RecSim. Fix syntax error in Db

LKSH218/iocBoot/iocLKSH218-IOC-01/st-common.cmd
=> changes for recsim mode

LKSH460/LKSH460-IOC-01App/Db/lakeshore460.db, LKSH460/LKSH460-IOC-01App/Db/lakeshore460_channels.template, LKSH460/iocBoot/iocLKSH460-IOC-01/st-common.cmd
Unit value PVs have been added to the IOC to allow user scientists to log values without them varying if they switch units. 
For example, when logging the raw device reading, if the user changes units the value of the readback will spike dramatically as it changes from Tesla to Gauss.
By adding FIELD:TESLA and FIELD:GAUSS PVs, we can maintain the overall log of the readback regardless of which unit we are in. Below, the units are changed from Tesla to Gauss but the RAW:GAUSS value remains unchanged. 
[Ticket 2887](https://github.com/ISISComputingGroup/IBEX/issues/2887)
See also: [OPI pull request](https://github.com/ISISComputingGroup/ibex_gui/pull/651)
See also: [Test Files pull request](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/62)
---
- [PV …
=> Ticket2887 display raw field readings

LINMOT/LINMOT-IOC-01App/Db/motor.substitutions, LINMOT/iocBoot/iocLINMOT-IOC-01/st.cmd, MCLEN/MCLEN-IOC-01App/Db/motor.substitutions
See https://github.com/ISISComputingGroup/IBEX/issues/2202
Turn on asyn trace on the linmot and mclennan, confirm that they both poll the motor position every second.
---
=> Ticket 2202: Added polling for the mclennan and linmot

BKHOFF/BKHOFF-IOC-01App/Db/IMAT.substitutions, BKHOFF/iocBoot/iocBKHOFF-IOC-01/st-common.cmd
Update BKHOFF Db files for axis record, also adjust high and low limits to reflect current range
See ISISComputingGroup/IBEX#3037
These are the current files as being used on IMAT, so already tested there
---
=> Use axis record DB files

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
Add an alarm to the manager mode so that it goes red in the spangle banner when manager mode is on
https://github.com/ISISComputingGroup/IBEX/issues/3010
- When Manager mode = No, text appears black in banner
- When Manager mode = Yes, text appears red in banner
Flash reviewed and approved by @John-Holt-Tessella 
---
=> Ticket3010 extend banner

HVCAEN/iocBoot/iocHVCAEN-IOC-01/st.cmd, HVCAEN/iocBoot/iocHVCAENSIM-IOC-01/st.cmd
The severity of being on or ramping up and down has been changed from a minor alarm to a macro, defaulting to no alarm.
See also:
https://github.com/ISISComputingGroup/EPICS-HVCAENx527/pull/2
https://github.com/ISISComputingGroup/IBEX/issues/3004
Put the IOC into sim mode.
caput TE:[Host]:CAEN:hv0:0:SIM YES
Change the status, make sure it has the correct severity level when using defaults and also when macro is set.
caput TE:[Host]:CAEN:hv0:0:SIM:0:status 1
caput TE:[Host]:CAEN:hv0:0:SIM:0:status 2
caput TE:[Host]:CAEN:hv0:0:SIM:0:status 3
---
- [Record …
=> Macro for severity of being on and ramping up or down

IPS/iocBoot/iocIPS-IOC-01/config.xml, IPS/iocBoot/iocIPS-IOC-01/st.cmd
@GDH-ISIS requested that the comms macros should not be user-configurable
=> Remove comms macros from ips

ITC503/iocBoot/iocITC503-IOC-01/config.xml, ITC503/iocBoot/iocITC503-IOC-01/st.cmd
@GDH-ISIS requested that the comms parameters should not be user-configurable
=> Remove comms macros from ITC. Values cannot be changed.

TPG300/iocBoot/iocTPG300-IOC-01/st-common.cmd
Added Devsim mode to TPG300 IOC to allow testing of an emulator for TPG300.
Related to Issue [#3214](https://github.com/ISISComputingGroup/IBEX/issues/3214).
- Runs in Devsim mode correctly.
- Runs in Recsim mode correctly.
---
=> Added Devsim mode to TPG300 IOC.

GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
Added env variables to ignore record loads for other GALIL motors.
[#3225](https://github.com/ISISComputingGroup/IBEX/issues/3225)
No `maclib` errors occur when running any GALIL motor.
---
=> Ticket3225: IOC: Larmor motion  set points

MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd
See https://github.com/ISISComputingGroup/IBEX/issues/3468.
The problem was fixed by restarting the MOXA. The underlying problem seems to only occur after some time of use, similar to https://github.com/ISISComputingGroup/IBEX/issues/3006. This change brings the handshaking more in line with the Labview in an attempt to fix it.
Confirm this fix is on VESUVIO and either go down and confirm it moves or trust that I moved it earlier today.
---
- [Finishing …
=> Ticket 3468: Attempted to fix mclennan delay issue

MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor-init.cmd
Changed the name of a macro in the McLennan IOC boot files to appropriately set the Open/Closed stepper mode
https://github.com/ISISComputingGroup/IBEX/issues/3470
- Note this will not be reflected in the status LED in the OPI, but can be verified by issuing command `xQM` over putty, where `x` is an axis number
=> Fix misspelled IOC macro

Makefile
Stops SEPRTR being built on linux where there is no DAQmx, a dependency for this module
https://github.com/ISISComputingGroup/IBEX/issues/3408
---
=> Prevent separator module being built on linux

DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml, DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/config.xml, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd
Added macro to Eurotherm and Danfysik IOCs for setting the calibration directory to a local one instead of the default common directory.
Also removed macros from Danfysik IOCs for setting arbitrary calibration dirs. It's not currently used anywhere as far as I can see and users might accidentally break the IOC if either of the entered value exceeds the EPICS 40 character limit.
https://github.com/ISISComputingGroup/IBEX/issues/2133
For both Eurotherm and Danfysik IOCs:
---
- [Finishing …
=> Ticket2133 multiple calibration directories

GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
Removes the simulation specific commands which execute when the IOC is booting in favour of an IOC macro, set in the IOC test framework. This points to a directory in motorExtensions/settings which contains the minimum required files for the IOC to boot. 
https://github.com/ISISComputingGroup/IBEX/issues/3623
---
=> Ticket3623 loq aperture

KNR1050/iocBoot/iocKNR1050-IOC-01/config.xml, KNR1050/iocBoot/iocKNR1050-IOC-02/config.xml
Rework based on the linked ticket.
- Changed the config.xml to include a correct device name and description
- Updated KNR1050_02 device to include a redirect in the config.xml to read from the _01 devices's config.xml
Fixes: https://github.com/ISISComputingGroup/IBEX/issues/3262
- A correct device name and description is shown in the IBEX GUI ioc configuration and device manager screens.
---
- [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing- …
=> Ticket3262: Updated config to have clear description and second ioc redirect.

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd
- Added two PVs for each active Eurotherm to check if the temperature is above or below the max or min values of the calibration file selected for that active Eurotherm.
- Load in a `calibration_range` aSub record for each active Eurotherm to check the calibration file for that Eurotherm.
[#3770](https://github.com/ISISComputingGroup/ibex_gui/pull/842)
---
- IOC responds correctly …
=> Ticket3770 check when reading is out of range

IPS/IPS-IOC-01App/Db/ips.db, IPS/iocBoot/iocIPS-IOC-01/config.xml, IPS/iocBoot/iocIPS-IOC-01/st.cmd
Add stability voltage macro and set the default to 0.1V as seen in the Labview (adjusted from 1V originally).
Add settings for sweep and max field. Table created in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/OxfordInstrumentsIPS.
https://github.com/ISISComputingGroup/IBEX/issues/2765
1) Stability voltage can be set as a macro
1) Calc show stability voltage is set.
---
- [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/IOC-Finishing-To …
=> Make stability volatge a macro

NGPSPSU/iocBoot/iocNGPSPSU-IOC-01/config.xml, NGPSPSU/iocBoot/iocNGPSPSU-IOC-01/st-common.cmd
Convert NGPS driver from using serial to TCP
https://github.com/ISISComputingGroup/IBEX/issues/3944
Macros are appropriately set for TCP comms
---
=> Use TCP rather than serial.

KHLY2400/KHLY2400-IOC-01App/Db/KHLY2400.db
Removes chained seq records to reduce the number of messages sent out. Each record which changes a parameter on the device also triggers its readback record to increase device responsiveness.
https://github.com/ISISComputingGroup/IBEX/issues/4063
---
=> Ticket4063 keithley ux improvements

LKSH340/LKSH340-IOC-01App/src/build.mak, ROTSC/ROTSC-IOC-01App/src/build.mak
Fix sedquencer library order for 2.2 compatibility
See ISISComputingGroup/IBEX#4253
* IOC builds
---
=> Fix seq libraries

NIMATRO/NIMATRO-IOC-01App/src/build.mak
Adds necessary libraries for nima trough to build statically
https://github.com/ISISComputingGroup/IBEX/issues/4263
Easiest way to test is to do the following (will take a while, it is building the whole tree!)
```
cd C:\instrument\apps\epics
config_env.bat
set EPICS_HOST_ARCH=windows-x64-static
make
```
You could also try building just the nima trough but you'll need to build all of it's dependencies statically first, so it's probably easier to just build everything.
---
- [Finishing …
=> Add pcre and pcrecpp

ASTRIUM/ASTRIUM-IOC-01App/Db/astrium.db, ASTRIUM/ASTRIUM-IOC-01App/protocol/astrium.proto
- Workaround a hardware issue in the astrium choppers by re-sending the phase setpoint explicitly after setting the speed setpoint.
- Set various comms timeouts to appropriate values based on testing with the hardware.
https://github.com/ISISComputingGroup/IBEX/issues/4123
See above
---
=> Fix sim records. Add timeouts to protocol.

ITC503/ITC503-IOC-01App/Db/ITC503.db
Renames the heater PV to reflect it's purpose (to write a per cent value). Adds an alarm to indicate the device is in local-only mode.
https://github.com/ISISComputingGroup/IBEX/issues/4033
---
=> Rename PV and add alarm

ATTOCUBE/ATTOCUBE-IOC-01App/Db/single_axis.substitutions
See https://github.com/ISISComputingGroup/IBEX/issues/4611
The attocube had a silly default speed, causing tests to fail as it was going too fast for the test to pick up. This reduces the speed
* Rebuild the attocube
* Confirm it moves at a sensible speed
---
=> Ticket 4611: Reduced default speed for attocube

TWINCAT/Makefile, TWINCAT/TWINCAT-IOC-01App/Db/Makefile, TWINCAT/TWINCAT-IOC-01App/Makefile, TWINCAT/TWINCAT-IOC-01App/protocol/Makefile, TWINCAT/TWINCAT-IOC-01App/src/Makefile, TWINCAT/TWINCAT-IOC-01App/src/TWINCAT-IOC-01Main.cpp, TWINCAT/TWINCAT-IOC-01App/src/build.mak, TWINCAT/configure/CONFIG, TWINCAT/configure/CONFIG_SITE, TWINCAT/configure/Makefile, TWINCAT/configure/RELEASE, TWINCAT/configure/RULES, TWINCAT/configure/RULES.ioc, TWINCAT/configure/RULES_DIRS, TWINCAT/configure/RULES_TOP, TWINCAT/iocBoot/Makefile, TWINCAT/iocBoot/iocTWINCAT-IOC-01/Makefile, TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.cmd, TWINCAT/iocBoot/iocTWINCAT-IOC-01/st.cmd
See https://github.com/ISISComputingGroup/IBEX/issues/3991
Note that this was the minimum required to get the IOC running and talking with a device. No GUI etc. has been made yet.
See https://github.com/ISISComputingGroup/BeckhoffPLCCode/pull/19
---
=> Ticket 3991: Added TWINCAT ioc based on tcIoc

EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd
Flow control was previously being set before the port was created, resulting in an error.
* Run the IOC on master (without devsim/recsim)
* Confirm there are errors in the output along the lines of cannot find port "L0"
* Run the IOC on this branch
* Errors are gone
---
=> Fixed Eurotherm flow control order

Makefile, OERCONE/Makefile, OERCONE/OERCONE-IOC-01App/Db/Makefile, OERCONE/OERCONE-IOC-01App/Makefile, OERCONE/OERCONE-IOC-01App/src/Makefile, OERCONE/OERCONE-IOC-01App/src/OERCONE-IOC-01Main.cpp, OERCONE/OERCONE-IOC-01App/src/build.mak, OERCONE/OERCONE-IOC-02App/Db/Makefile, OERCONE/OERCONE-IOC-02App/Makefile, OERCONE/OERCONE-IOC-02App/src/Makefile, OERCONE/OERCONE-IOC-02App/src/OERCONE-IOC-02Main.cpp, OERCONE/configure/CONFIG, OERCONE/configure/CONFIG_SITE, OERCONE/configure/Makefile, OERCONE/configure/RELEASE, OERCONE/configure/RULES, OERCONE/configure/RULES.ioc, OERCONE/configure/RULES_DIRS, OERCONE/configure/RULES_TOP, OERCONE/iocBoot/Makefile, OERCONE/iocBoot/iocOERCONE-IOC-01/Makefile, OERCONE/iocBoot/iocOERCONE-IOC-01/config.xml, OERCONE/iocBoot/iocOERCONE-IOC-01/st-common.cmd, OERCONE/iocBoot/iocOERCONE-IOC-01/st.cmd, OERCONE/iocBoot/iocOERCONE-IOC-02/Makefile, OERCONE/iocBoot/iocOERCONE-IOC-02/config.xml, OERCONE/iocBoot/iocOERCONE-IOC-02/st.cmd
Adds an Oerlikon Centre-One Pressure Gauge IOC
[ISISComputingGroup/IBEX#4115](https://github.com/ISISComputingGroup/IBEX/issues/4115)
1. The solution must provide equivalent functionality to the existing SECI VI.
2. I can view the pressure from the UI.
3. I can obtain the pressure via a genie_python script.
---
=> Ticket4115 add ioc oercone

JSCO4180/JSCO4180-IOC-01App/src/build.mak, JSCO4180/configure/RELEASE
Fix library order for static linking on Linux
* Linux static build works
* Other builds unaffected
---
=> Fix jasco library order

HELIOX/HELIOX-IOC-01App/src/build.mak, Makefile
* Add missing EDTIC directory
* swap HELIOX gsl library order for linux
* builds now pass initial "checkdirs" test 
* linux static build works
---
=> Add missing edtic dir

EDTIC/EDTIC-IOC-01App/src/build.mak
* Adjust link order for linux static build
* linux static build works
---
=> Adjust link order for linux static

Makefile
Exclude TWINCAT with VS2010
---
=> Exclude TWINCAT on VS2010

HVCAEN/iocBoot/iocHVCAEN-IOC-01/config.xml, HVCAEN/iocBoot/iocHVCAEN-IOC-01/st.cmd
Added macros that can be set on the HVCAEN IOC so we can talk to crates in multiple locations (up to 8)
https://github.com/ISISComputingGroup/IBEX/issues/4182
---
=> Added HVCAEN ability to add crates through macros (tested on NDADETMON)

CP2800/CP2800-IOC-01App/src/build.mak, OERCONE/OERCONE-IOC-01App/src/build.mak, TWINCAT/TWINCAT-IOC-01App/src/build.mak
Fix static build library issues (missing sscan)
Check Static build now works in jenkins
---
=> Static build fixes

GALIL/GALIL-IOC-01App/Db/galil_userdef_records8.substitutions
Make deadband default to -ve
https://github.com/ISISComputingGroup/IBEX/issues/4602
1. New motor has default motor off deadband -1 (see galil engineering screen)
---
=> Make default -ve

GAMRY/iocBoot/iocGAMRY-IOC-01/config.xml
Updated the description of the Gamry IOC for clarity. This driver is for the ISIS created Gamry trigger and not individual Gamry devices.
=> Ticket 4834 - Gamry IOC description update

CRYOSMS/CRYOSMS-IOC-01App/Makefile, CRYOSMS/CRYOSMS-IOC-01App/src/CRYOSMS-IOC-01Main.cpp, CRYOSMS/CRYOSMS-IOC-01App/src/Makefile, CRYOSMS/CRYOSMS-IOC-01App/src/build.mak, CRYOSMS/CRYOSMS-IOC-02App/Makefile, CRYOSMS/CRYOSMS-IOC-02App/src/CRYOSMS-IOC-02Main.cpp, CRYOSMS/CRYOSMS-IOC-02App/src/Makefile, CRYOSMS/Makefile, CRYOSMS/configure/CONFIG, CRYOSMS/configure/CONFIG_SITE, CRYOSMS/configure/Makefile, CRYOSMS/configure/RELEASE, CRYOSMS/configure/RULES, CRYOSMS/configure/RULES.ioc, CRYOSMS/configure/RULES_DIRS, CRYOSMS/configure/RULES_TOP, CRYOSMS/iocBoot/Makefile, CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/Makefile, CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml, CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd, CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st.cmd, CRYOSMS/iocBoot/iocCRYOSMS-IOC-02/Makefile, CRYOSMS/iocBoot/iocCRYOSMS-IOC-02/config.xml, CRYOSMS/iocBoot/iocCRYOSMS-IOC-02/st.cmd
Added CRYOSMS IOC with basic functionality
https://github.com/ISISComputingGroup/IBEX/issues/4826
IOC starts correctly and passes the basic system tests.
---
=> Ticket651 add ioc cryosms

CRYOSMS/CRYOSMS-IOC-01App/src/build.mak
Fix cryomag Linux static link
---
=> Fix linux link

CRYOSMS/CRYOSMS-IOC-01App/src/build.mak
Updated case of lib name in the makefile to fix the RH6 Static Linux build.
=> Updated CRYOSMS library name

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
Added a string record which is used by the GUI to display the status of the motors.
https://github.com/ISISComputingGroup/IBEX/issues/3562
---
=> Ticket3562 Added string record for motor movement

KEPCO/KEPCO-IOC-04App/Db/Makefile, KEPCO/KEPCO-IOC-04App/Makefile, KEPCO/KEPCO-IOC-04App/protocol/Makefile, KEPCO/KEPCO-IOC-04App/src/KEPCO-IOC-04Main.cpp, KEPCO/KEPCO-IOC-04App/src/Makefile, KEPCO/iocBoot/iocKEPCO-IOC-04/Makefile, KEPCO/iocBoot/iocKEPCO-IOC-04/config.xml, KEPCO/iocBoot/iocKEPCO-IOC-04/st.cmd
EMU needed another instance of the kepco IOC as they are using 3 for the 3 axes of the zero-field system and need one more for the vertical steering magnet
n/a
- IOC tests work for IOC 4
---
=> Add 4th Kepco IOC

MUONTPAR/MUONTPAR-IOC-01App/Db/Makefile, MUONTPAR/MUONTPAR-IOC-01App/Db/muon_tpar.db, MUONTPAR/MUONTPAR-IOC-01App/Makefile, MUONTPAR/MUONTPAR-IOC-01App/src/MUONTPAR-IOC-01Main.cpp, MUONTPAR/MUONTPAR-IOC-01App/src/Makefile, MUONTPAR/MUONTPAR-IOC-01App/src/build.mak, MUONTPAR/Makefile, MUONTPAR/configure/CONFIG, MUONTPAR/configure/CONFIG_SITE, MUONTPAR/configure/Makefile, MUONTPAR/configure/RELEASE, MUONTPAR/configure/RULES, MUONTPAR/configure/RULES.ioc, MUONTPAR/configure/RULES_DIRS, MUONTPAR/configure/RULES_TOP, MUONTPAR/iocBoot/Makefile, MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/Makefile, MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml, MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd, Makefile
Adds an IOC holding the muon tpar files.
This is needed for the muon beamlines, to let them configure which tpar file they need to use in their configuration. We could not use the existing INSTETC PVs as they are not configurable in the config.
=> Add MUONTPAR ioc

DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
Fixed incorrect units in the description of macros for tolerance in the Danfysik IOC.
=> Fix description of tolerance macros

LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd
Fixed: Ensured port creation occurred before input/output EOS as this is required by real devices.
=> Hot Fix: terminators created after port created as required by real device

SM300/iocBoot/iocSM300-IOC-01/st-common.cmd, SMC100/iocBoot/iocSMC100-IOC-01/st-common.cmd
Add motion setpoints and other standard extensions to the SMC100. Tidy the copied place to highlight possible error.
https://github.com/ISISComputingGroup/IBEX/issues/5165
- motion setpoints load
---
=> Add motion setpoint axes etc to SMC100 and make same as SM300

MK2CHOPR/iocBoot/iocMK2CHOPR-IOC-01/st-common.cmd, MK3CHOPR/MK3CHOPR-IOC-01App/Db/mk3_common.db, MK3CHOPR/iocBoot/iocMk3CHOPR-IOC-01/st.cmd
Define mock chopper in RECSIM as well as DEVSIM
See ISISComputingGroup/IBEX#5354
* ioc system tests work in recsim
---
=> Fix recsim mode for ioc system tests

TWINCAT/iocBoot/iocTWINCAT-IOC-01/config.xml, TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua
See https://github.com/ISISComputingGroup/IBEX/issues/4919
tcIOC can now support both the old ISIS code and the new code from the Twincat collaboration, this is controlled through an environment variable. The LUA code was also updated.
---
=> Ticket 4919: Update tcIOC to specify PLC version

ISISDAE/iocBoot/iocISISDAE-IOC-01/dllPath_extra.bat
Add path to VS2015 libraries if not otherwise installed, this will only affect "system tests debug" and not any running instrument
* system tests debug can start isisdae
---
=> Add VS2015 debug libraries if needed

FERMCHOP/FERMCHOP-IOC-01App/src/keep_sp_and_rbv_in_sync.st
* Fix issue with setpoint changing
* Add additional state to remove use of epicsThreadSleep()
See ISISComputingGroup/IBEX#5383
* IOC units tests pass
---
=> Recode to fix setpoint/readback sync issue and also remove use of epicsThreadSleep

ROTSC/ROTSC-IOC-01App/src/build.mak
Fix library link order for linux
=> Fix library order

MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
config.xml was too strict not allowing DB1.P1 which is required for running with some card names.
https://github.com/ISISComputingGroup/IBEX/issues/5497
https://github.com/ISISComputingGroup/IBEX/issues/5497#issuecomment-668023501
---
=> Allow . in card macro names

KHLY2001/KHLY2001-IOC-01App/src/build.mak
Fix library order for linux static build
---
=> Fix library order for linux static

FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db
See https://github.com/ISISComputingGroup/IBEX/issues/5644
* On master, with a running instrument start the fermichopper ioc with devsim `%PYTHON% run_tests.py -t fermichopper_merlin -a -tm DEVSIM`.
* Confirm that ARINST is logging a large number of messages about `FERMCHOP_01:STATUS:RAW.VAL exceeds 80 chars`
* Switch to this branch and rebuild the IOC
* Restart ARINST
* Re run the ioc and confirm that there is no longer any logging
---
- [Finishing …
=> Remove logging RAW status

KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml, KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
Add macro to allow configuration of resetting the kepco and resending setpoints on startup of the ioc.
https://github.com/ISISComputingGroup/IBEX/issues/3185
---
=> Ticket3185 remote mode reliability

TEKMSO4104B/configure/RELEASE
* Run `make clean uninstall && make` 
---
=> Changed TEKMSO4104 dependencies to be more explicit

GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALILMUL_01_positions.req, GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALILMUL_01_settings.req, GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALIL_01_positions.req, GALILMUL/iocBoot/iocGALILMUL-IOC-01/GALIL_01_settings.req, GALILMUL/iocBoot/iocGALILMUL-IOC-01/IMATStagesMenu.req, GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-common.cmd
Fixed autosave. See https://github.com/ISISComputingGroup/IBEX/issues/5836
* Remove `$(IFNOTDEVSIM)` from lines 68 and 71 in st-common
* Put the following into globals.txt:
```
GALILMUL_01__DEVSIM=yes
GALILMUL_01__MTRCTRL1=01
GALILMUL_01__MTRCTRL2=02
```
* Start GALILMUL_01
* Set a setting on MTR0101 and MTR0201
* Wait 1 minute
* Restart GALILMUL_01
* Confirm settings on MTR0101 and MTR0201 are what was previously set
---
- [Finishing …
=> Ticket 5836: Fix autosave for GALILMUL

KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml, KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
After chatting with @DominicOram and @John-Holt-Tessella we decided that by default we should keep the behaviour of the kepco's the same (i.e. not resetting and resending setpoints) and to set the config up in more specific cases to do this.
---
=> Set default to 0

LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd, MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-common.cmd
~~gem_jaws IOC system tests were failing because jaws.db had not been called correctly. This was caused by the IFGEMJAWS macro not being defined correctly, define it here.~~ This is now fixed by writing the macros correctly in the IOC_Test_Framework
mercuryitc IOC system tests were failing because it was not loading the MercuryGlobal.db as it was looking in the wrong place. Use correct macro to look in the right place.
https://github.com/ISISComputingGroup/IBEX/issues/5888
---
- [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manua …
=> Fix ioc system tests

KEPCO/KEPCO-IOC-01App/src/build.mak
To fix https://epics-jenkins.isis.rl.ac.uk/job/EPICS_IOC_Windows7_x64_static_CLEAN/1050/consoleText
Check this has the same dependencies as the Eurotherm, which does build the FileList stuff ok
---
=> Fix static build by being explicit about all dependencies

PULL_REQUEST_TEMPLATE.md
See https://github.com/ISISComputingGroup/IBEX/issues/2185
---
=> Ticket 2185: Updated pr template

LINKAM95/iocBoot/iocLINKAM95-IOC-01/st-common.cmd
Just make the st.cmd use $DEVICE consistently and don't log so much
N/A found as part of fixing IOC system tests
tests still run (you will need latest LEWIS for them to run)
---
=> Use device consistently and stop logging all asyn comms

HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags.db, HIFIMAGS/HIFIMAGS-IOC-01App/Db/mainpsu.db
After a demo to the IS they wanted a change to the labels from `Not Ramping` to  `Leads at B` and `Ramping` to `Leads to 0`
Whilst testing with LabVIEW found a few changes were needed
Changed ZNAM and ONAM for the 'ramping' leads records
Aliases to allow shorter PV names for use with LabVIEW
See https://github.com/ISISComputingGroup/IBEX/issues/6224
Run the IOC in RECSIM mode
Check the OPI has the new labels
Run the latest version of `LabVIEW Modules\Instruments\HIFI\Cryomag\Client Side\HIFI - Cryomag.llb\HIFI - Cryomag - Front Panel.vi` from Source Safe (or ask for a copy) with no errors and updating as appropriate
The labels for the lead ramp records are changed from `Not Ramping` to  `Leads at B` and `Ramping` to `Leads to 0`
The VI runs as expected
---
- [PV …
=> Change ramping labels and interaction with LabVIEW

MUONTPAR/MUONTPAR-IOC-01App/Db/muon_tpar.db, MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml, MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd
MuSR requires 2 tpar files for two separate ITC503s in the same configuration, add an option in the MUONTPAR ioc to have a second. Default to empty if not used.
---
=> MUONTPAR: Add an optional second tpar file

MCLEN/MCLEN-IOC-01App/Db/motor.substitutions, MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd
See https://github.com/ISISComputingGroup/IBEX/issues/5739
Stopped polling the motor when its moving as this causes jogs to stop
* Pull all associated branches
* Make motor/master and ioc/MCLEN
* Run the mclennan ioc tests and confirm they pass
* In the mclennan motor.db remove the SDIS field from the SCAN record (as on master) and confirm jogging IOC test fails
* In the mclennan motor.db remove the PP from the OUT field from the SCAN record and confirm the other test fails (proving that we are still correctly polling when stationary)
---
- [Record …
=> Ticket 5739: Change mclennan to talk to an emulator

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Add millivolt (mV) metric to EUROTHRM SENSOR EPICS record
Eurotherm: display millivolts somewhere
#6571
https://github.com/ISISComputingGroup/IBEX/issues/6571
EUROTHRM SENSOR can return millivolts (mV) metric with associated value
---
- [ NA ] A copy of the manual has been placed on the shared drive
- [ NA ] Pertitent information has been stored in the [wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Specific-Device-IOC)
- [ NA ] Does the IOC conform to IBEX standards? …
=> Update EPICS EUROTHRM SENSOR record to include mV metric

ILM200/iocBoot/iocILM200-IOC-01/st-common.cmd
Fixes NOT using ISOBUS on the ILM200 - the `IFNOT_USE_ISOBUS` was being used incorrectly from the `stringiftest` statement, as was setting `ISOBUS=""` as EPICS was evaluating the macro as undefined. This doesn't stop the proto file from working and we got an ILM200 working without ISOBUS on WISH. 
Difficult without a device - set USE_ISOBUS to `No` and check DB gets loaded correctly - before this will have failed to load both the channel and common Dbs. 
---
- [Record simulation](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Record-Simul …
=> Fixes not using ISOBUS on ILM

GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-motor-controller.cmd
https://github.com/ISISComputingGroup/IBEX/issues/6785
---
=> Changed file name is setting area to galilmul(controller name) 

DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml, DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd
See https://github.com/ISISComputingGroup/IBEX/issues/6624
* In the epics directory run `make iocstartups` (this will expose the baud rate in the config)
* Start your instrument
* Add a Danfysik 9X00 to your configs
* Confirm in the log it has a baud rate of 115200
* Confirm setting the baud rate in the config changed it in the logs
---
=> Ticket 6624: Added variable baud rate based on model number

HVCAEN/iocBoot/iocHVCAEN-IOC-01/config.xml, HVCAEN/iocBoot/iocHVCAEN-IOC-01/st.cmd
Add macros to allow specifying CAE crate type
See ISISComputingGroup/IBEX#6926
* specifying crate type fixes issue on SANS2D (where it has been hotfixed)
---
=> Add HVCAENSYSTYPE macro for crate type

BKHOFF/iocBoot/iocBKHOFF-IOC-01/st-common.cmd, CONEXAGP/iocBoot/iocCONEXAGP-IOC-01/st-common.cmd, GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd, GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-motor-controller.cmd, INSTETC/INSTETC-IOC-01App/Db/INSTETC.db, LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd, NWPRTXPS/iocBoot/iocNWPRTXPS-IOC-01/st-common.cmd, PIMOT/iocBoot/iocPIMOT-IOC-01/st-common.cmd, SM300/iocBoot/iocSM300-IOC-01/st-common.cmd, SMC100/iocBoot/iocSMC100-IOC-01/st-common.cmd, TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua
Use new `motorController.db` for per controller PVs, `motorUtil.db` is per IOC not per controller 
See ISISComputingGroup/IBEX#6923
* Db Loads without error and `AXES_NUM` PV is available
---
=> Fix num axes

EUROTHRM/README.md, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/config.xml, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd, EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-timing.cmd
This PR was created to complete work as part of [#7026](https://github.com/ISISComputingGroup/IBEX/issues/7026)
The changes made in this PR extend the number of channels from 7 to 10 for a single Eurotherm unit.
From the [EPICS-IOC_Test_Framework](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework), checkout [THIS PR](https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/524) and run the eurotherm system test from an EPICS terminal to first test channel 1 by passing `python run_tests.py -t eurotherm` into your cmd. (*_channel 1 is still the default channel tested_*)
Repeat the system test for other channels by altering the address and IOC variable. I have provided an example below of the changes needed to test channel 10.
```python
ADDRESS = "A010" # Change this …
```
=> EUROTHERM Extend Number of channels to 10

TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/config.xml, TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st-common.cmd
IP Address for this device was hardcoded. This is not always correct, e.g. INTER use a device with a different address, so I changed it to be configurable via macro.
How to test functionality:
1. Pull changes
2. Run `/EPICS/EPICSTerm.bat` and in it, run command `make iocstartups`
3. Start Server
4. Add a TEKAFG3XXX ioc, confirm there is an `ADDR` macro with sensible description
5. Set a value for it and save config. Confirm the macro gets set correctly: look for line `$(IFNOTDEVSIM) $(IFNOTRECSIM) vxi11Configure("GPIB0", $(ADDR), 0, 0.0,"inst0", 0, 0)` in `/instrument/var/logs/TEKAFG...`
=> TEKAFG3XXX: Add macro for IP address

DG645/iocBoot/iocDG645-IOC-01/config.xml, KHLY6517/iocBoot/iocKHLY6517-IOC-01/config.xml
There was an alert being displayed in various places (for example when running make iocstartups) that those 2 IOCs dont have hasfault for their port macro so I fixed it here
=> added hasdefault=no to both troublesome IOCs

TPG300/iocBoot/iocTPG300-IOC-01/st-common.cmd
https://github.com/ISISComputingGroup/IBEX/issues/5877
Acceptance Criteria
The IOC supports a pressure threshhold setting
The IOC reports the relay contact status of the TPG300 device (see Notes below)
The OPI displays an indication if the pressure is below the threshhold setting (red LED, lit=BELOW/unlit=ABOVE)
The OPI displays the relay contact status (green LED, lit=ON/unlit=OFF)
I can query the pressure threshhold status via genie_python
I can query the relay contact status via genie_python
---
- [Record …
=> Ticket5877 Added new records to be loaded

FINS/FINS-IOC-01App/Db/zoom-vacuum-commands.template
When testing the new do_trans/sans scripts we noticed that the monitor for zoom was set differently so we updated it to use the equivalent pv as sans2d. When testing further we noticed that the monitor was now not being set. Investigation showed that there were some extra colons in the db so the address was slightly wrong. We have removed the colons and confirmed that now it works corretly.
=> Removed extra colons from zoom vacuum db

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
The alarm was appearing occasionally for users and scientists were
simply telling them to ignore it. If the error is not significant, we
don't want users ignoring more important alarms, so let's not display
this one. It'll still be logged, so we can always check that.
1. Check that this PV no longer appears in the list of alarms for the Eurotherm in the GUI. 
Fixes ISISComputingGroup/IBEX#3019
The alarm no longer appears to our users. 
---
- [Finishing …
=> Remove `RETRYCNT` alarm from Eurotherm

NCINDG/NCINDG-IOC-01App/src/build.mak
Add Iphlpapi.lib to fix static link error on static windows build
=> NCINDG: add Iphlpapi for static link

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Added new PV (`RAMP_FILE_NOT_DEFAULT`) to be able to check whether DIP and max output lookup file for ramping has **changed from the** specified **default** file.
[*Link to Ticket #4735*](https://github.com/ISISComputingGroup/IBEX/issues/4735)
- A message to remind the user when they change the default file but have not yet to turned lookup on
---
=> Ticket 4735

TRANTECH/TRANTECH-IOC-01App/src/build.mak
Move library location for linux one pass static linker
=> TRANTECH: move library for static linux link

MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
[Ticket #7322](https://github.com/ISISComputingGroup/IBEX/issues/7322)
Updated TEMP/LEVEL/PRESSURE macros from `^.*$` to ^.*[.].*$
Note: when macros were changed, all current mercury temp/level/pressure macro values adhered to the pattern (except the ones which are undefined as `""`, which is also valid)
---
=> Update level/pressure/temp macro patterns

TRANTECH/TRANTECH-IOC-03App/Db/Makefile, TRANTECH/TRANTECH-IOC-03App/Makefile, TRANTECH/TRANTECH-IOC-03App/src/Makefile, TRANTECH/TRANTECH-IOC-03App/src/TRANTECH-IOC-03Main.cpp, TRANTECH/TRANTECH-IOC-04App/Db/Makefile, TRANTECH/TRANTECH-IOC-04App/Makefile, TRANTECH/TRANTECH-IOC-04App/src/Makefile, TRANTECH/TRANTECH-IOC-04App/src/TRANTECH-IOC-04Main.cpp, TRANTECH/iocBoot/iocTRANTECH-IOC-03/Makefile, TRANTECH/iocBoot/iocTRANTECH-IOC-03/config.xml, TRANTECH/iocBoot/iocTRANTECH-IOC-03/st.cmd, TRANTECH/iocBoot/iocTRANTECH-IOC-04/Makefile, TRANTECH/iocBoot/iocTRANTECH-IOC-04/config.xml, TRANTECH/iocBoot/iocTRANTECH-IOC-04/st.cmd
Two additional Transtechnik IOCs are required for RIKENFE as two pairs are used for ARGUS and CHRONUS steering magnets.
Transtechnik IOCs 3 and 4 are built correctly 
Transtechnik IOCs 3 and 4 exist and function.
---
=> Added Transtechnik IOCs 3 and 4

BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-03/config.xml, BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-03/dllPath.bat, BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-03/runIOC.bat, Makefile, TEKOSC/Makefile, TEKOSC/TEKOSC-IOC-01App/Db/Makefile, TEKOSC/TEKOSC-IOC-01App/Makefile, TEKOSC/TEKOSC-IOC-01App/src/Makefile, TEKOSC/TEKOSC-IOC-01App/src/TEKOSC-IOC-01Main.cpp, TEKOSC/TEKOSC-IOC-01App/src/build.mak, TEKOSC/configure/CONFIG, TEKOSC/configure/CONFIG_SITE, TEKOSC/configure/Makefile, TEKOSC/configure/RELEASE, TEKOSC/configure/RULES, TEKOSC/configure/RULES.ioc, TEKOSC/configure/RULES_DIRS, TEKOSC/configure/RULES_TOP, TEKOSC/iocBoot/Makefile, TEKOSC/iocBoot/iocTEKOSC-IOC-01/Makefile, TEKOSC/iocBoot/iocTEKOSC-IOC-01/config.xml, TEKOSC/iocBoot/iocTEKOSC-IOC-01/st-common.cmd, TEKOSC/iocBoot/iocTEKOSC-IOC-01/st.cmd
Adds the non-support stuff for the Tektronix IOC. The device connects through an IP address provided via a macro. 
This PR also adds an 3rd background script IOC, which is just a copy of the second one. This is due to EMU already using two background scripts and therefore needing a 3rd if they want to collect images using the new script
ISISComputingGroup/IBEX#7318
1. The preamble and raw waveform data for each channel is accessible through blocks. 
2. The address of the device can be changed (it's common for its IP to have changed if it's been switched off for a while)
Note: There's a real device on my desk, ping me for the IP if testing remotely or just go and have a look at it. (Utility -> Utility Page -> I/O -> Ethernet Network Settings -> Change Instrument Settings)
Partially …
=> Add Tektronix Osc IOC and Additional Background Script IOC

DG645/iocBoot/iocDG645-IOC-01/config.xml, DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
This is much easier than having to faff about with hooking up a moxa.
The process of setting up the device is a bit more involved though.
The following settings need to be configured beforehand:
In the NET menu (SHIFT -> STO(NET)):
TCPIP = Enabled
DHCP = Enabled
Telnet = Enabled
Reset = Yes
Press the Enter Button
1. Then access the status menu (SHIFT -> 6(STATUS) and use the arrows to navigate to TCPIP Status.
2. Press 6 until you get to IP
3. Make a note of this IP
4. Input this IP into the macro within IBEX
5. Start the IOC
This IP will be reassigned if the device is down for a while. So the above process will need to be repeated.
Fixes ISISComputingGroup/IBEX#7426
- [Disable …
=> Allow the DG645 to be controlled via ethernet

DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
Fix the pattern that checks danfysik calib files to allow '.' (so you can enter calib files via IBEX rather than editing config.xml)
=> Fix dfkps calib file pattern to allow '.'

SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-01/config.xml
This controller can be used for both DISC and FERMI choppers.
https://github.com/ISISComputingGroup/IBEX/issues/6100
---
=> Ticket6100

Makefile
Do not build TC if no twincat on windows
=> Build TC only with twincat on windows

ASTRIUM/ASTRIUM-IOC-01App/src/Makefile, ASTRIUM/ASTRIUM-IOC-01App/src/build.mak, HVCAEN/HVCAEN-IOC-01App/src/Makefile, HVCAEN/HVCAEN-IOC-01App/src/build.mak, HVCAENA/HVCAENA-IOC-01App/src/Makefile, HVCAENA/HVCAENA-IOC-01App/src/build.mak, MK3CHOPR/MK3CHOPR-IOC-01App/src/Makefile, MK3CHOPR/MK3CHOPR-IOC-01App/src/build.mak
As ioc builds execute in parallel, a copy in of an external file must only be executed in the 01 IOC
=> Avoid a file copy race condition

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Fix errors like    IN:POLREF:EUROTHRM_01:A02:RAMP_FILE:SP scanAdd: I/O Intr not valid (no get_ioint_info)
Before PR, you should see above error even with an emulator. After PR merge no error message 
Error message no longer occurs
---
=> Eurotherm: Output records cannot be I/O Intr

RZBRP100/iocBoot/iocRZBRP100-IOC-01/config.xml
RZBRP100 was returning an error when trying to run `make iocstartups` from EPICS terminal, with a message saying that its PORT macro has no "hasDefault" attribute. This was added into RZBRP100-01's config.xml
=> Fixed macro having no 'hasDefault' value

MCLEN/MCLEN-IOC-01App/Db/mclen_motor_extra.db, MCLEN/MCLEN-IOC-01App/Db/motor.substitutions, MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml, MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor-init.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd, MCLEN/iocBoot/iocMCLEN-IOC-01/st.cmd
See ISISComputingGroup/IBEX#7727
---
=> Add more parameter setup, fix potential PCOF issue

NIMATRO/NIMATRO-IOC-01App/Db/controls.db, NIMATRO/iocBoot/iocNIMATRO-IOC-01/config.xml, NIMATRO/iocBoot/iocNIMATRO-IOC-01/st-common.cmd
Added Area, Speed, and Pressure macros to controls.db, config.xml, and st-common.cmd for the NIMA Trough, so that scientists using IBEX can set their own high and low limits for all three. If they do not specify their own limits, they will default to the current default highs and lows for those three respective values. 
https://github.com/ISISComputingGroup/IBEX/issues/7141
---
- [Finishing touches](https://github.com/ISISComputingGroup/ibex_developers_manual/w …
=> Area, speed, and pressure macros

MEASM905/MEASM905-IOC-01App/Db/Makefile, MEASM905/MEASM905-IOC-01App/Makefile, MEASM905/MEASM905-IOC-01App/protocol/Makefile, MEASM905/MEASM905-IOC-01App/src/MEASM905-IOC-01Main.cpp, MEASM905/MEASM905-IOC-01App/src/Makefile, MEASM905/MEASM905-IOC-01App/src/build.mak, MEASM905/Makefile, MEASM905/configure/CONFIG, MEASM905/configure/CONFIG_SITE, MEASM905/configure/Makefile, MEASM905/configure/RELEASE, MEASM905/configure/RULES, MEASM905/configure/RULES.ioc, MEASM905/configure/RULES_DIRS, MEASM905/configure/RULES_TOP, MEASM905/iocBoot/Makefile, MEASM905/iocBoot/iocMEASM905-IOC-01/Makefile, MEASM905/iocBoot/iocMEASM905-IOC-01/config.xml, MEASM905/iocBoot/iocMEASM905-IOC-01/st-common.cmd, MEASM905/iocBoot/iocMEASM905-IOC-01/st.cmd, Makefile
MEASM905, a Pressure Transducer in use on PEARL, has had device_generator.py run for its addition into IBEX.
[*Which ticket does this PR fix?*](https://github.com/ISISComputingGroup/IBEX/issues/6041)
All the necessary skeleton files that would have been created into this repo are present; none are missing. 
---
=> device_generator skeleton files created

DG645/DG645-IOC-01App/src/build.mak, DG645/iocBoot/iocDG645-IOC-01/auto_settings.req, DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
Add additional macros and refactor autosave calls to enable better use of configMenu. These defaults are no longer applied automatically on startup as other PRs on ticket make it read back from device instead 
See ISISComputingGroup/IBEX#7893
---
=> Pass additional macros for restore

LSICORR/iocBoot/iocLSICORR-IOC-01/Makefile, LSICORR/iocBoot/iocLSICORR-IOC-01/dllPath.bat, LSICORR/iocBoot/iocLSICORR-IOC-01/runIOC.bat, LSICORR/iocBoot/iocLSICORR-IOC-02/Makefile, LSICORR/iocBoot/iocLSICORR-IOC-02/dllPath.bat, LSICORR/iocBoot/iocLSICORR-IOC-02/runIOC.bat
Refactor LSI startup - there have been recent startup errors in system tests, amongst other things this change reduces the amount of items added to PATH that may have become an issue    
`run_all_tests.bat -t lsicorr` in `support\IOCSystemTests\master`
tests pass
---
=> Refactor LSI startup

ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/config.xml
Macro was using incorrect regex for optional decimal places due to typo'd underscore.
---
=> Fix Macro in ZFCNTRL

FERMCHOP/FERMCHOP-IOC-01App/src/fermi.cpp
Add newline to end of error messages, the consistent with other messages printed in file and also now seems to be required for log file unuit test
fermichopper maps and merlin tests now pass
---
=> Add newline to errors printed to fix tests

PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/config.xml, PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/st-daq.cmd
Missed error in DAQMx units macro name during testing and review.
Also changed default CJC (Cold Junction Compensation) value to match original VI.
Check units can be selected by changing IOC macro value.
Check values returned are plausible.
Units selectable and returned values reflect change (and reality)
---
=> Corrected macro name in DAQMX startup file, changed default CJC source

DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db, DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd
- Added the alarm field to Danfysik current PV so now shows up in alarm perspective.
- There was no default emulator port in Danfysik IOC startup file, added this.
[#8342](https://github.com/ISISComputingGroup/IBEX/issues/8342)
- Add and run Danfysik IOC in devsim mode and check that the Current PV e.g `*:DFKPS_01:CURR` gets added to the alarm tree.
- Run Danfysik emulator without supplying an emulator port and check that it successfully connects.
See ticket info
---
- [Finishing …
=> Added alarm field & default emulator port

LNDYISW/LNDYISW-IOC-03App/Db/Makefile, LNDYISW/LNDYISW-IOC-03App/Makefile, LNDYISW/LNDYISW-IOC-03App/src/LNDYISW-IOC-03Main.cpp, LNDYISW/LNDYISW-IOC-03App/src/Makefile, LNDYISW/LNDYISW-IOC-04App/Db/Makefile, LNDYISW/LNDYISW-IOC-04App/Makefile, LNDYISW/LNDYISW-IOC-04App/src/LNDYISW-IOC-04Main.cpp, LNDYISW/LNDYISW-IOC-04App/src/Makefile, LNDYISW/LNDYISW-IOC-05App/Db/Makefile, LNDYISW/LNDYISW-IOC-05App/Makefile, LNDYISW/LNDYISW-IOC-05App/src/LNDYISW-IOC-05Main.cpp, LNDYISW/LNDYISW-IOC-05App/src/Makefile, LNDYISW/LNDYISW-IOC-06App/Db/Makefile, LNDYISW/LNDYISW-IOC-06App/Makefile, LNDYISW/LNDYISW-IOC-06App/src/LNDYISW-IOC-06Main.cpp, LNDYISW/LNDYISW-IOC-06App/src/Makefile, LNDYISW/iocBoot/iocLNDYISW-IOC-03/Makefile, LNDYISW/iocBoot/iocLNDYISW-IOC-03/config.xml, LNDYISW/iocBoot/iocLNDYISW-IOC-03/st.cmd, LNDYISW/iocBoot/iocLNDYISW-IOC-04/Makefile, LNDYISW/iocBoot/iocLNDYISW-IOC-04/config.xml, LNDYISW/iocBoot/iocLNDYISW-IOC-04/st.cmd, LNDYISW/iocBoot/iocLNDYISW-IOC-05/Makefile, LNDYISW/iocBoot/iocLNDYISW-IOC-05/config.xml, LNDYISW/iocBoot/iocLNDYISW-IOC-05/st.cmd, LNDYISW/iocBoot/iocLNDYISW-IOC-06/Makefile, LNDYISW/iocBoot/iocLNDYISW-IOC-06/config.xml, LNDYISW/iocBoot/iocLNDYISW-IOC-06/st.cmd
Adds 4 more LNDYISW IOCs. 
https://github.com/ISISComputingGroup/IBEX/issues/8516
To review, `make` in ioc\master\lndyisw and then go to support\lndyisw\master\system_tests\, change the DEVICE_PREFIX to 3, add iocnum=3 in the call to get_default_ioc_dir() and check all tests pass. 
---
=>  add 4 more lindy IOCs

MUONTPAR/MUONTPAR-IOC-01App/src/build.mak
Fix linux static build of MUONTPAR - linux static linking is only single pass so libraries need to be listed in dependency order 
---
=> Linux static lib reorder to fix MUONTPAR build

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Adding a record called check_read, which forward links to the RBV record every 10 seconds, in order to periodically scan if that record is disconnected. READ_RESTART record has also been changed to inherit the alarm severity of RBV record, so if it is disconnected, READ_RESTART will go into alarm, instead of continually trying to proc the READ record, thus causing communication block for other potential eurotherm IOCs wanting to connect. The IVOA field is meant to stop record outputs of a calcout, so that it won't process the READ record.
- https://github.com/ISISComputingGroup/IBEX/issues/8310
---
- [Disable …
=> Add check_read record to periodically check RBV record, make read_restart a calcout to not proc READ record if RBV is in alarm

INSTETC/configure/RELEASE, PSCTRL/PSCTRL-IOC-01App/src/build.mak, PSCTRL/configure/RELEASE, RUNCTRL/configure/RELEASE
Remove use of MASTER_RELEASE in some IOCs, this can lead to very long PATHs and sometimes IOC start failure
See ISISComputingGroup/IBEX#8558
* iocs build as before
---
=> Remove use of MASTER_RELEASE

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
Add quotation marks around a field value so that the file gets loaded
=> add quotation marks in eurotherm db to fix system tests

Makefile, NFIPM/Makefile, NFIPM/NFIPM-IOC-01App/Makefile, NFIPM/NFIPM-IOC-01App/db/Makefile, NFIPM/NFIPM-IOC-01App/db/motor.substitutions, NFIPM/NFIPM-IOC-01App/db/motorSim.substitutions, NFIPM/NFIPM-IOC-01App/src/Makefile, NFIPM/NFIPM-IOC-01App/src/NFIPM-IOC-01Main.cpp, NFIPM/NFIPM-IOC-01App/src/build.mak, NFIPM/configure/CONFIG, NFIPM/configure/CONFIG_SITE, NFIPM/configure/Makefile, NFIPM/configure/RELEASE, NFIPM/configure/RULES, NFIPM/configure/RULES.ioc, NFIPM/configure/RULES_DIRS, NFIPM/configure/RULES_TOP, NFIPM/iocBoot/Makefile, NFIPM/iocBoot/iocNFIPM-IOC-01/Makefile, NFIPM/iocBoot/iocNFIPM-IOC-01/axes.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/config.xml, NFIPM/iocBoot/iocNFIPM-IOC-01/jaws.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/motionsetpoints.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/st-axes.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/st-common.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/st-ctrl.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/st-max-axis.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/st-motor.cmd, NFIPM/iocBoot/iocNFIPM-IOC-01/st.cmd
Added an IOC for the new focus intelligent picometer for use in the litron laser power control. There was already a motor support for this, so just ioc work to setup a motor nesecart
[*Which ticket does this PR fix?*](https://github.com/ISISComputingGroup/IBEX/issues/8331)
Motor can be used in conjunction with OPI to recreate capabilities of this vi:
---
=> Added ioc for the new focus intellgient picometer

DG645/iocBoot/iocDG645-IOC-01/config.xml, DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
See https://github.com/ISISComputingGroup/IBEX/issues/6090 for original ticket.
See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Litron-Laser-Timing-Control-(Stanford-DG645) for newly created wiki page.
This creates a new macro in the DG645 IOC that allows for a litron laser timing control 'mode'. Using this will load an extra db file which allows the use of extra PVs for this use case.
=> Litronlasertiming#6090

G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/st-common.cmd, IPS/IPS-IOC-01App/Db/ips.db
For Group3 Hall Probe, Inhibit taking field readings for two seconds after a range change.
A patch has already been deployed to HIFI and testing is underway.
8704
EPICS records in group3hallprobe_probe.db OK
New macros provided in st-common.cmd OK
---
=> Ticket8704: Range change timer

DG645/iocBoot/iocDG645-IOC-01/st-common.cmd
I think `COM` is incorrect - seen error on EMU
[2025-03-06 10:43:52] INFO -- asynInterposeCOM options extending and perhaps overriding those of lower interface.
[2025-03-06 10:43:52] WARNING -- Can't set serial port parameters: Device says WON'T 0.
---
=> Remove COM from DG645

EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-comms-modbus.cmd, MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-e1210.cmd, MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-e1240.cmd, MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-e1242.cmd, MOXA12XX/iocBoot/iocMOXA12XX-IOC-01/st-e1262.cmd, PRE4500/iocBoot/iocPRE4500-IOC-01/st-comms-modbus.cmd, SCHNDR/iocBoot/iocSCHNDR-IOC-01/devices/GEMGateValve.cmd, SCHNDR/iocBoot/iocSCHNDR-IOC-01/devices/RIKENFE.cmd
Fix modbus datatypes after upgrade to 3.x
(Though this PR is part of a larger ticket, it is the only PR that would affects ibex code that is actually run. The other modules that are part of the ticket are example code. Hence putting this one forward early as flash review to fix system tests)  
See ISISComputingGroup/IBEX#8779
basically check that only the seventh argument to function has changed and the integer has become a string as per maping on ticket
---
- [PV naming](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/conventions/PV-Naming.html).
- [Disable records](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/testing/Disable-records.html)
- [Record simulation](https://isiscomputinggroup.github.io/ibex_develope …
=> Fix modbus data types

NGEM/iocBoot/iocNGEM-IOC-01/config.xml
Fixed the REGEX in ngem config.xml to allow the default value (localhost) to pass.
=> Correct regex to allow default value to pass
