ISISComputingGroup/EPICS-ioc

AG33220A/iocBoot/iocAG33220A-IOC-01/st.cmd
AG3631A/iocBoot/iocAG3631A-IOC-01/st.cmd
EUROTHERM/iocBoot/iocEUROTHERM-IOC-01/st.cmd
EUROTHERM/iocBoot/iocEUROTHERM-IOC-02/st.cmd
GALIL/iocBoot/iocGALIL-IOC-01/st.cmd
HAMEG8123/iocBoot/iocHAMEG8123-IOC-01/st.cmd
HAMEG8123/iocBoot/iocHAMEG8123-IOC-02/st.cmd
JULABO/iocBoot/iocJULABO-IOC-01/st.cmd
JULABO/iocBoot/iocJULABO-IOC-02/st.cmd
STPS350/iocBoot/iocSTPS350-IOC-01/st.cmd
STSR400/iocBoot/iocSTSR400-IOC-01/st.cmd
TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st.cmd
TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-02/st.cmd
TEKDMM40X0/iocBoot/iocTEKDMM4040-IOC-01/st.cmd
TEKMSO4104B/iocBoot/iocTEKMSO4104B-IOC-01/st.cmd
TEKMSO4104B/iocBoot/iocTEKMSO4104B-IOC-02/st.cmd
TPG300/iocBoot/iocTPG300-IOC-01/st.cmd
TPG300/iocBoot/iocTPG300-IOC-02/st.cmd
TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/st.cmd
TTIEX355P/iocBoot/iocTTIEX355P-IOC-02/st.cmd

Need to update your top EPICS repository to get latest version of configure/MASTER_RELEASE before checking

Change use of SUPPORT macro to MASTER_RELEASE macros

---

INSTETC/INSTETC-IOC-01App/Db/experiment_data.db
ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd

See [PR108](https://github.com/ISISComputingGroup/ibex_gui/pull/108)

Ticket689: Speed up of RB setting

---

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
INSTETC/INSTETC-IOC-01App/Db/inst_real_parameters.template
INSTETC/INSTETC-IOC-01App/Db/inst_string_parameters.template
INSTETC/INSTETC-IOC-01App/src/INSTETC-IOC-01Include.dbd
INSTETC/INSTETC-IOC-01App/src/build.mak
INSTETC/INSTETC-IOC-01App/src/instetcInclude.dbd

Needs to be done in connection with pr ISISComputingGroup/EPICS-asubFunctions#2

Ticket999 add queued pv set

---

INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd

See https://github.com/ISISComputingGroup/ICP/issues/4

Ensure that facility pvs are loaded into the MySQL database

---

HVCAEN/HVCAEN-IOC-01App/Db/Makefile
HVCAEN/HVCAEN-IOC-01App/src/build.mak
HVCAEN/HVCAENSIM-IOC-01App/Db/Makefile
HVCAEN/HVCAENSIM-IOC-01App/src/build.mak
HVCAEN/iocBoot/iocHVCAEN-IOC-01/st.cmd
HVCAEN/iocBoot/iocHVCAENSIM-IOC-01/st.cmd

Needs to be done together with Ticket1008_update_caen branch in HVCAENx527 repository  
Initially test CAEN is still working as expected

Update to work with new caen

---

MK3CHOPPER/iocBoot/iocMk3CHOPPER-IOC-01/Makefile

ISISComputingGroup/IBEX/issues/1081

Uncommented the line stopping RunIOC.bat being created

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS.db
DFKPS/iocBoot/iocDFKPS-IOC-01/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-02/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-03/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-04/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-05/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-06/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-07/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-08/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-09/st.cmd
TDK_LAMBDA_GENESYS/GENESYS-IOC-01App/Db/TDK_Lambda_Genesys.db
TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/st-psu.cmd

Relates to ISISComputingGroup/IBEX#1170
Corrections to various files found to be necessary after testing the IOCs with live systems. See the issue for full details.

Ticket1170 bug fixes

---

FINS/FINS-IOC-01App/Db/imat-attn.template

Add blank units for status

---

FINS/FINS-IOC-01App/Db/imat-attn.template

STATUS is now an MBBI record, and open/close can now be done
via a single MOVE PV
Needs testing on IMAT as not able to properly test myself beforehand
See ISISComputingGroup/IBEX#1304

Extend STATUS and add MOVE PVs

---

MERCURY_ITC/MERCURY-IOC-01App/src/build.mak

This is where missing exit function is kept
See ISISComputingGroup/IBEX#1299

Add asubFunctions library

---

DELFTSHEAR/DELFTSHEAR-IOC-01App/Db/Makefile
DELFTSHEAR/DELFTSHEAR-IOC-01App/Db/shear.db
DELFTSHEAR/DELFTSHEAR-IOC-01App/Makefile
DELFTSHEAR/DELFTSHEAR-IOC-01App/protocol/DELFTSHEAR_lv.xml
DELFTSHEAR/DELFTSHEAR-IOC-01App/protocol/DELFTSHEAR_nv.xml
DELFTSHEAR/DELFTSHEAR-IOC-01App/protocol/Makefile
DELFTSHEAR/DELFTSHEAR-IOC-01App/src/DELFTSHEAR-IOC-01Main.cpp
DELFTSHEAR/DELFTSHEAR-IOC-01App/src/Makefile
DELFTSHEAR/DELFTSHEAR-IOC-01App/src/build.mak
DELFTSHEAR/Makefile
DELFTSHEAR/configure/CONFIG
DELFTSHEAR/configure/CONFIG_SITE
DELFTSHEAR/configure/Makefile
DELFTSHEAR/configure/RELEASE
DELFTSHEAR/configure/RULES
DELFTSHEAR/configure/RULES.ioc
DELFTSHEAR/configure/RULES_DIRS
DELFTSHEAR/configure/RULES_TOP
DELFTSHEAR/iocBoot/Makefile
DELFTSHEAR/iocBoot/iocDELFTSHEAR-IOC-01/Makefile
DELFTSHEAR/iocBoot/iocDELFTSHEAR-IOC-01/st.cmd
Makefile

See ISISComputingGroup/IBEX#1400

Add shear cell control

---

MERCURY_ITC/MERCURY-IOC-01App/Db/Makefile
MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st.cmd

This should be tested and merged at the same time as ISISComputingGroup/EPICS-MercuryiTC#2

Ticket 1285: updated makefile and st.cmd to load new db file

---

INSTETC/INSTETC-IOC-01App/Db/Makefile
INSTETC/INSTETC-IOC-01App/Db/inst_exclusive.db
INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd

Include some additional records to allow for different security groups to limit access exclusively to the server
Relates to https://github.com/ISISComputingGroup/IBEX/issues/1210
Rebuild INSTETC_01 and start INSTETC_01
If running as part of an instrument access the console for INSTETC_01
Run the following at the ioc prompt: `dbgrep *EXCL*`, this should return 1 record in the format MYPVPREFIX:CS:EXCLUSIVE
Add some appropriate globals to globals.txt (e.g. EXCLUSIVE2=:EXC2) - note that the : is needed
Restart INSTETC_01
Run the following at the ioc prompt: `dbgrep *EXCL*`, this should return 1 record in the format MYPVPREFIX:CS:EXCLUSIVE and records relating to the macros set in globals.txt (e.g. MYPVPRFIX:CS:EXCLUSIVE:EXC2)
INSTETC_01 has records relating to macro entries in globals.txt …

Ticket1210 access security changes

---

DFKPS/DFKPS-IOC-10App/Db/Makefile
DFKPS/DFKPS-IOC-10App/Makefile
DFKPS/DFKPS-IOC-10App/protocol/Makefile
DFKPS/DFKPS-IOC-10App/src/DFKPS-IOC-10Main.cpp
DFKPS/DFKPS-IOC-10App/src/Makefile
DFKPS/DFKPS-IOC-11App/Db/Makefile
DFKPS/DFKPS-IOC-11App/Makefile
DFKPS/DFKPS-IOC-11App/protocol/Makefile
DFKPS/DFKPS-IOC-11App/src/DFKPS-IOC-11Main.cpp
DFKPS/DFKPS-IOC-11App/src/Makefile
DFKPS/iocBoot/iocDFKPS-IOC-10/Makefile
DFKPS/iocBoot/iocDFKPS-IOC-10/config.xml
DFKPS/iocBoot/iocDFKPS-IOC-10/st.cmd
DFKPS/iocBoot/iocDFKPS-IOC-11/Makefile
DFKPS/iocBoot/iocDFKPS-IOC-11/config.xml
DFKPS/iocBoot/iocDFKPS-IOC-11/st.cmd

Add Danfysiks 10 and 11
https://github.com/ISISComputingGroup/IBEX/issues/1512
Danfysiks 10 and 11 exist and can be controlled as in 1-9
---

Add Danfysiks 10 and 11

---

LKSH218/LKSH218-IOC-01App/protocol/Makefile
LKSH218/iocBoot/iocLKSH218-IOC-01/st-common.cmd
LKSH218/iocBoot/iocLKSH218-IOC-01/st.cmd
LKSH218/iocBoot/iocLKSH218-IOC-02/st.cmd

Fixes from IRIS
https://github.com/ISISComputingGroup/IBEX/issues/1587
See also: https://github.com/ISISComputingGroup/genie_python/pull/47
Test that can start and run Lakeshore 218 IOC with port set in GUI.
Test that you can install ipython and that the profile get created as part of the process.
---

Fixes from IRIS Release. Build protocol file. Use PORT as macro not TTY.

---

SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-02/st-common.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-02/st.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-03/st-common.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-03/st.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-04/st-common.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-04/st.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-05/st-common.cmd
SKFCHOPPER/iocBoot/iocSKFCHOPPER-IOC-05/st.cmd

Add David's IMAT files - see ISISComputingGroup/IBEX#1737
Already working on IMAT
---

David's latest versions from IMAT

---

MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml

I've updated the McLennan IOC macro descriptions to better describe what they are
https://github.com/ISISComputingGroup/IBEX/issues/1708
The new macros make sense
---

Improve macro descriptions

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_8000_status.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_8800_status.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db

As part of https://github.com/ISISComputingGroup/IBEX/issues/1491

Removed duplicate fields

---

INSTETC/INSTETC-IOC-01App/Db/svn-revision.db.tmpl

Set the master versions of server to be 0.0.0 on master branch so it is clear it is not a release version.
https://github.com/ISISComputingGroup/IBEX/issues/1549
Reported version of client on master branch is obviously not a release version
---

Set master branch version to 0.0.0

---

KEPCO/iocBoot/iocKEPCO-IOC-01/st.cmd
KEPCO/iocBoot/iocKEPCO-IOC-02/st.cmd

The Kepco IOC should now start successfully in simulation mode if that option is chosen in the gui.
https://github.com/ISISComputingGroup/IBEX/issues/1938
---

Kepco simulation mode bug fix

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd

Load dae diagnostics DB on startup
See ISISComputingGroup/IBEX#1846
Diagnostic PVs available as per above ticket
---

Add loading of dae diags

---

FINS/FINS-IOC-01App/Db/Makefile
FINS/FINS-IOC-01App/Db/zoom-vacuum.substitutions
FINS/FINS-IOC-01App/Db/zoom-vacuum.template

Stub DB records for the PLC on zoom which will be updated with "real" content as part of https://github.com/ISISComputingGroup/IBEX/issues/1232
https://github.com/ISISComputingGroup/IBEX/issues/2210
---

Add skeleton DB files for zoom vacuum

---

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db

Tickets 2082 and 2083
(acceptance criteria are listed on the GUI pull request)
---

Add manager mode PV

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd

This update the DAE ioc to use changes introduced in ISISComputingGroup/EPICS-isisdae#20
See ISISComputingGroup/IBEX#2104 and ISISComputingGroup/EPICS-isisdae#20
Tests in above EPICS-isisdae PR pass
---

Add second web driver

---

BKHOFF/BKHOFF-IOC-01App/Db/IMAT.substitutions
BKHOFF/BKHOFF-IOC-01App/Db/Makefile
BKHOFF/BKHOFF-IOC-01App/Makefile
BKHOFF/BKHOFF-IOC-01App/src/BKHOFF-IOC-01Main.cpp
BKHOFF/BKHOFF-IOC-01App/src/Makefile
BKHOFF/BKHOFF-IOC-01App/src/build.mak
BKHOFF/BKHOFF-IOC-02App/Db/Makefile
BKHOFF/BKHOFF-IOC-02App/Makefile
BKHOFF/BKHOFF-IOC-02App/src/BKHOFF-IOC-02Main.cpp
BKHOFF/BKHOFF-IOC-02App/src/Makefile
BKHOFF/BKHOFF-IOC-02App/src/build.mak
BKHOFF/Makefile
BKHOFF/configure/CONFIG
BKHOFF/configure/CONFIG_SITE
BKHOFF/configure/Makefile
BKHOFF/configure/RELEASE
BKHOFF/configure/RULES
BKHOFF/configure/RULES.ioc
BKHOFF/configure/RULES_DIRS
BKHOFF/configure/RULES_TOP
BKHOFF/iocBoot/Makefile
BKHOFF/iocBoot/iocBKHOFF-IOC-01/Makefile
BKHOFF/iocBoot/iocBKHOFF-IOC-01/config.xml
BKHOFF/iocBoot/iocBKHOFF-IOC-01/st-common.cmd
BKHOFF/iocBoot/iocBKHOFF-IOC-01/st.cmd
BKHOFF/iocBoot/iocBKHOFF-IOC-02/Makefile
BKHOFF/iocBoot/iocBKHOFF-IOC-02/st.cmd

Add ISIS bechhoff IOC (based on ESS one)
ISISComputingGroup/IBEX#1889
Unable to test until deployed on IMAT due to private network, so only visual code checks possible
---

Add initial beckhoff implementation

---

JULABO/JULABO-IOC-01App/Db/FL300.db
JULABO/JULABO-IOC-01App/Db/FP50_MH.db
JULABO/iocBoot/iocJULABO-IOC-01/st-common.cmd

Added record simulation to Julabo and added some missing SIM records
https://github.com/ISISComputingGroup/IBEX/issues/2168
Just check that you can put the IOC into record simulation via the IBEX GUI and that you can set values.
---

Ticket #2168: Added recsim to julabo

---

BKHOFF/iocBoot/iocBKHOFF-IOC-02/config.xml

Add a missing config.xml for BKHOFF_02
https://github.com/ISISComputingGroup/IBEX/issues/2336
- Stop server
- Run make iocstartups
- Start server
- Create a config with BKHOFF_02 IOC
- Confirm that a description is displayed in the edit configuration dialog
---

Add missing config.xml

---

MCLEN/iocBoot/iocMCLEN-IOC-01/st-motor.cmd

Pass a debug flag to the sequencer to we can switch debug output on and off at startup
Done as part of https://github.com/ISISComputingGroup/IBEX/issues/2289
When "DEBUG" is set to 1, the console output for the motor shows the state transitions in the sequencer. Try moving the motor to home to see some transitions
---

Pass debug flag to sequencer

---

TPG26x/iocBoot/iocTPG26x-IOC-01/st-common.cmd

https://github.com/ISISComputingGroup/IBEX/issues/2379
This adds a port to use for the emulator to the TPG26x

Ticket2379: Create TPG26x Emulator

---

JULABO/iocBoot/iocJULABO-IOC-01/st-common.cmd

Very minor changes to st-common.cmd to make it match the style of the other IOCs that have emulators and tests for the testing framework.

Modified st-common's dev sim stuff to be more standard

---

PSCTRL/PSCTRL-IOC-01App/src/build.mak

Adds build.mak entry so that PSCTRL doesn't complain on startup
https://github.com/ISISComputingGroup/IBEX/issues/1781
---

Add build.mak entry

---

KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd
KEPCO/iocBoot/iocKEPCO-IOC-01/st.cmd
KEPCO/iocBoot/iocKEPCO-IOC-02/st.cmd

Macros for devsim for KEPCO
---

Added macros

---

AG33220A/AG33220A-IOC-01App/Db/agilent33220A.db
AG33220A/iocBoot/iocAG33220A-IOC-01/config.xml
AG33220A/iocBoot/iocAG33220A-IOC-01/st.cmd

Added more PVs to the AG33220A, created an emulator and wrote IOC tests for it.
- Run new tests in the IOC testing framework
- Check that you can set the IP macro from the gui
- Make sure you can still connect to the device
- Make sure VOLT:HIGH, VOLT:LOW, VOLT:OFFS and VOLT work the same in the emulator as they do on the device

Ticket2479: Emulator for AG33220A

---

EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd

Fixed typo causing eurotherm IOC tests to fail
---

Moved changing the ramp directory

---

IEG/IEG-IOC-01App/Db/ieg.db

Fixes IEG to work with Matt North's new protocol.
https://github.com/ISISComputingGroup/IBEX/issues/2632
- Agrees with new protocol (see sharepoint site)
---

Update error descriptions

---

EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-common.cmd

Changed senor directory to point at an example
---

Ticket2465: Fix eurotherm temp ramping

---

SAMPOS/SAMPOSApp/Db/controls_multi.template

Removes unneeded alarm
https://github.com/ISISComputingGroup/IBEX/issues/2594
- Alarm no longer appears for SAMPOS ioc when the SP is undefined
---

Remove spurious alarm on SAMPOS SP records

---

FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db

Adds extra diagnostic records
https://github.com/ISISComputingGroup/IBEX/issues/2660
Same things are now available in IOC as in labview
---

Add more diagnostic records

---

MK3CHOPR/MK3CHOPR-IOC-01App/Db/mk3_common.db

Update sim record

---

MK3CHOPR/MK3CHOPR-IOC-01App/Db/mk3.db
MK3CHOPR/MK3CHOPR-IOC-01App/src/build.mak
MK3CHOPR/iocBoot/iocMk3CHOPR-IOC-01/st.cmd

Adds access security to the MK3 chopper IOC, on a per-chopper basis.
https://github.com/ISISComputingGroup/IBEX/issues/2718
You can set up access security by adding `MK3CHOPR_01__ASG1=MANAGER` to your `globals.txt` (this will set up access security for only chopper 1). Use `ASG2` etc. for other choppers.
---

Ticket2718 mk3 access security

---

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db
INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/2769
Adds a locally archived PV that points to the central PV for the instrument's shutter status.
* Ensure you have the latest version of the archive engine 
* Start INSTETC in RECSIM
* Start JSON bourne locally (https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Web-Dashboard#developmenttesting)
* Confirm the shutter status is on the webpage
* Confirm the shutter status changes when the simulated PV changes
---
- …

Ticket2769: Display shutter status on web dashboard

---

INSTRON/INSTRON-IOC-01App/Db/controls_channel_specific.db
INSTRON/INSTRON-IOC-01App/Db/controls_waveform.db

Add MS links (to propagate alarms) to instron DBs
Ensure you have https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/49
https://github.com/ISISComputingGroup/IBEX/issues/2667
---

Add MS links

---

INSTETC/INSTETC-IOC-01App/Db/inst_string_parameters.substitutions

Add measurement IDs
See ISISComputingGroup/IBEX#2910
PVs available
---

Add measurement ids

---

MERCURY_ITC/MERCURY-IOC-01App/Db/Makefile
MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml
MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st.cmd

PR onto release branch
Equivalent PR onto master:
https://github.com/ISISComputingGroup/EPICS-ioc/pull/219 
Ticket:
https://github.com/ISISComputingGroup/IBEX/issues/2840

Ticket2840 extend mercury cryostat for gem

---

INSTRON/INSTRON-IOC-01App/Db/controls_waveform.db

Same as https://github.com/ISISComputingGroup/EPICS-ioc/pull/223 but this one is onto the release branch

Don't stop the waveform if WAVE:START is active

---

GEMORC/GEMORC-IOC-01App/Db/GEMORC.db
GEMORC/configure/RELEASE

Fix a few protocol and communication issues with the GEMORC following testing with the hardware
https://github.com/ISISComputingGroup/IBEX/issues/2808
---

Ticket2808 gemorc commissioning

---

LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd

Added recsim mode to linmots to fix the tests added in https://github.com/ISISComputingGroup/IBEX/issues/2138

Linmots now correctly run in recsim

---

SCHNDR/SCHNDR-IOC-01App/Db/SCHNDR.db
SCHNDR/iocBoot/iocSCHNDR-IOC-01/config.xml
SCHNDR/iocBoot/iocSCHNDR-IOC-01/st-common.cmd

Add working GEM implementation ISISComputingGroup/IBEX#2798

Ticket2798 add schneider plc

---

KEPCO/KEPCO-IOC-03App/Db/Makefile
KEPCO/KEPCO-IOC-03App/Makefile
KEPCO/KEPCO-IOC-03App/protocol/Makefile
KEPCO/KEPCO-IOC-03App/src/KEPCO-IOC-03Main.cpp
KEPCO/KEPCO-IOC-03App/src/Makefile
KEPCO/iocBoot/iocKEPCO-IOC-03/Makefile
KEPCO/iocBoot/iocKEPCO-IOC-03/config.xml
KEPCO/iocBoot/iocKEPCO-IOC-03/st.cmd

Created third IOC for KEPCO.
[3005](https://github.com/ISISComputingGroup/IBEX/issues/3005)
There is a third IOC for KEPCO.
---

Ticket 3005: Add framework for third IOC

---

GAMRY/GAMRY-IOC-01App/Db/GAMRY.db
GAMRY/GAMRY-IOC-01App/Db/Makefile
GAMRY/GAMRY-IOC-01App/Makefile
GAMRY/GAMRY-IOC-01App/protocol/GAMRY.protocol
GAMRY/GAMRY-IOC-01App/protocol/Makefile
GAMRY/GAMRY-IOC-01App/src/GAMRY-IOC-01Main.cpp
GAMRY/GAMRY-IOC-01App/src/Makefile
GAMRY/GAMRY-IOC-01App/src/build.mak
GAMRY/Makefile
GAMRY/configure/CONFIG
GAMRY/configure/CONFIG_SITE
GAMRY/configure/Makefile
GAMRY/configure/RELEASE
GAMRY/configure/RULES
GAMRY/configure/RULES.ioc
GAMRY/configure/RULES_DIRS
GAMRY/configure/RULES_TOP
GAMRY/iocBoot/Makefile
GAMRY/iocBoot/iocGAMRY-IOC-01/Makefile
GAMRY/iocBoot/iocGAMRY-IOC-01/st.cmd

Initial implementation of ISISComputingGroup/IBEX#2642 for quick test on IMAT

Add basic gamry for IMAT

---

SPINFLIPPER306015/SPINFLIPPER-IOC-01App/Db/SPINFLIPPER-IOC-01.db
SPINFLIPPER306015/iocBoot/iocSPINFLIPPER-IOC-01/st.cmd

added recsim record and st.cmd recsim fixes

---

LKSH336/iocBoot/iocLKSH336-IOC-01/st-common.cmd

recsim changes

---

HAMEG8123/HAMEG8123-IOC-01App/Db/devHameg_8123.db
HAMEG8123/iocBoot/iocHAMEG8123-IOC-01/st-common.cmd
LINKAM95/LINKAM95-IOC-01App/Db/LINKAM95.db
LINKAM95/iocBoot/iocLINKAM95-IOC-01/st-common.cmd
LINKAM95/iocBoot/iocLINKAM95-IOC-01/st.cmd
LINKAM95/iocBoot/iocLINKAM95-IOC-02/st.cmd

Enable rec sim from macro in IOC

---

FINS/iocBoot/iocFINS-IOC-01/fins-sim.cmd
FINS/iocBoot/iocFINS-IOC-01/st-common.cmd

Add FINS startup file for use when in simulation mode. Part of ISISComputingGroup/IBEX#3007
When merged, IOC test framework should run
* IOC test framework runs
---

Load fins-sim.cmd when in simulation mode

---

FERMCHOP/FERMCHOP-IOC-01App/Db/fermchop.db
FERMCHOP/FERMCHOP-IOC-01App/src/build.mak
FERMCHOP/FERMCHOP-IOC-01App/src/fermi.cpp
FERMCHOP/FERMCHOP-IOC-01App/src/fermichopper.c
FERMCHOP/FERMCHOP-IOC-01App/src/fermichopper.dbd
FERMCHOP/FERMCHOP-IOC-01App/src/fermichopper.h
FERMCHOP/FERMCHOP-IOC-01App/src/keep_sp_and_rbv_in_sync.st
FERMCHOP/FERMCHOP-IOC-01App/src/seqPVmacros.h
FERMCHOP/iocBoot/iocFERMCHOP-IOC-01/st.cmd

Works around the bugs described in https://github.com/ISISComputingGroup/IBEX/issues/2988 at a driver level, rather than an instrument script level.
https://github.com/ISISComputingGroup/IBEX/issues/2988
---

Ticket2988

---

PULL_REQUEST_TEMPLATE.md

Update PR template to include an explicit check for flow control.
https://github.com/ISISComputingGroup/IBEX/issues/3085
- PR template is appropriate.
---

Update PR template to include an explicit check for flow control.

---

BKHOFF/BKHOFF-IOC-01App/src/build.mak
BKHOFF/iocBoot/iocBKHOFF-IOC-01/BKHOFF_01_positions.req
BKHOFF/iocBoot/iocBKHOFF-IOC-01/BKHOFF_01_settings.req
BKHOFF/iocBoot/iocBKHOFF-IOC-01/motorsim.cmd
BKHOFF/iocBoot/iocBKHOFF-IOC-01/st-common.cmd

Load autosave setting into BECKHOFF
See ISISComputingGroup/IBEX#3191
* when a motor record value is changed it is remembered on restart 
---

Add loading of autosave files

---

LKSH218/iocBoot/iocLKSH218-IOC-01/st-common.cmd
LKSH336/iocBoot/iocLKSH336-IOC-01/st-common.cmd

Correct incorrect connection strings
https://github.com/ISISComputingGroup/IBEX/issues/3229

Make lakeshore 218 autoconnect and lakeshore 336 use ip address

---

LICENSE

Add LICENCE file to EPICS-ioc
This partially fixes #3321
#3321, #2991
---

Ticket3321_add_licence_to_ioc_generator

---

BKHOFF/BKHOFF-IOC-01App/Db/IMAT.substitutions
BKHOFF/BKHOFF-IOC-01App/src/build.mak
BKHOFF/configure/RELEASE
BKHOFF/iocBoot/iocBKHOFF-IOC-01/st-common.cmd

Revert back to using motor record instead of axis record
Part of ISISComputingGroup/IBEX#3343
* Builds and runs in simulation mode
---

Revert back to original motor record

---

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db
EUROTHRM/iocBoot/iocEUROTHRM-IOC-01/st-euro.cmd

sCalc record concatenates new unit with '/min' and pushed output to `RATE.EGU`
https://github.com/ISISComputingGroup/IBEX/issues/3263
- Ramp units are displayed correctly
- Ramp units change if new calibration file uses different units
---

Ticket3263 eurotherm ramp units

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/liveview.cmd
ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd

Add PVs and startup commands to enable live view
ISISComputingGroup/IBEX#3381
* A liveview device screen can be added
---

Ticket3381 live view

---

INDFURN/INDFURN-IOC-01App/Makefile
INDFURN/INDFURN-IOC-01App/src/INDFURN-IOC-01Main.cpp
INDFURN/INDFURN-IOC-01App/src/Makefile
INDFURN/INDFURN-IOC-01App/src/build.mak
INDFURN/Makefile
INDFURN/configure/CONFIG
INDFURN/configure/CONFIG_SITE
INDFURN/configure/Makefile
INDFURN/configure/RELEASE
INDFURN/configure/RULES
INDFURN/configure/RULES.ioc
INDFURN/configure/RULES_DIRS
INDFURN/configure/RULES_TOP
INDFURN/iocBoot/Makefile
INDFURN/iocBoot/iocINDFURN-IOC-01/Makefile
INDFURN/iocBoot/iocINDFURN-IOC-01/config.xml
INDFURN/iocBoot/iocINDFURN-IOC-01/st.cmd
Makefile

Adds IOC for induction furnace that will be used on GEM and POLARIS
https://github.com/ISISComputingGroup/IBEX/issues/3296
---

Ticket3296 add ioc indfurn

---

MCLEN/iocBoot/iocMCLEN-IOC-01/motorExtensions.cmd
MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd

For https://github.com/ISISComputingGroup/IBEX/issues/3455

Add ability for mclennan to call motor extensions

---

LKSH218/LKSH218-IOC-03App/Db/Makefile
LKSH218/LKSH218-IOC-03App/Makefile
LKSH218/LKSH218-IOC-03App/protocol/Makefile
LKSH218/LKSH218-IOC-03App/src/LKSH218-IOC-03Main.cpp
LKSH218/LKSH218-IOC-03App/src/Makefile
LKSH218/iocBoot/iocLKSH218-IOC-03/Makefile
LKSH218/iocBoot/iocLKSH218-IOC-03/config.xml
LKSH218/iocBoot/iocLKSH218-IOC-03/st.cmd

Added a third lakeshore 218 IOC clone
https://github.com/ISISComputingGroup/IBEX/issues/3629
---

Added third lakeshore IOC

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/liveview.cmd
ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd

Load  the area detector stats plugin into the DAE live view 
See ISISComputingGroup/IBEX#3630
* Plugin loads and e.g, MaxValue is calculated as per ticket description
---

Add area detector stats plugin

---

LKSH218/LKSH218-IOC-04App/Db/Makefile
LKSH218/LKSH218-IOC-04App/Makefile
LKSH218/LKSH218-IOC-04App/protocol/Makefile
LKSH218/LKSH218-IOC-04App/src/LKSH218-IOC-04Main.cpp
LKSH218/LKSH218-IOC-04App/src/Makefile
LKSH218/iocBoot/iocLKSH218-IOC-04/Makefile
LKSH218/iocBoot/iocLKSH218-IOC-04/config.xml
LKSH218/iocBoot/iocLKSH218-IOC-04/st.cmd

- Added a fourth Lakeshore 218 IOC.
[#3696](https://github.com/ISISComputingGroup/IBEX/issues/3696)
---

Added a fourth lakeshore

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_8000_status.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_8800_status.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db

This ticket is part of [link](https://github.com/ISISComputingGroup/IBEX/issues/3641)
Fixes: https://github.com/ISISComputingGroup/IBEX/issues/3641
See associated link.
---

Dansfysik: Fixed simulation mode for Dansfysik.

---

TDK_LAMBDA_GENESYS/iocBoot/iocGENESYS-IOC-01/config.xml

Ticket:
https://github.com/ISISComputingGroup/IBEX/issues/3667

Added address macro.

---

RKNPS/RKNPS-IOC-01App/Db/Makefile
RKNPS/RKNPS-IOC-01App/Db/riken_psu_banner.db
RKNPS/iocBoot/iocRKNPS-IOC-01/st.cmd

Adds PVs for the banner on rikenfe (the scientists wanted custom messages rather than a plain on/off)
https://github.com/ISISComputingGroup/IBEX/issues/3615
- Same as on NDXRIKENFE
---

Add banner messages in own DB

---

DMA4500M/iocBoot/iocDMA4500M-IOC-01/config.xml

Add DMA4500M conf

---

CYBAMAN/CYBAMAN-IOC-01App/Db/cybaman_axes.template

Fix test for cybaman by targetting correct pv and pulling the error through

add alarm interest

---

SDTEST/iocBoot/iocSDTEST-IOC-01/config.xml
SDTEST/iocBoot/iocSDTEST-IOC-01/st-common.cmd
SDTEST/iocBoot/iocSDTEST-IOC-01/st-port-common.cmd
SDTEST/iocBoot/iocSDTEST-IOC-01/st-port-ip.cmd
SDTEST/iocBoot/iocSDTEST-IOC-01/st-port-ipcom.cmd
SDTEST/iocBoot/iocSDTEST-IOC-01/st-port-serial.cmd

Allow SDTEST to talk to a tcpip port
See ISISComputingGroup/IBEX#3999
SDTEST can talk to a simple TCPIP server
---

Add IP option as well as RFC2217 serial ip

---

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db

See: https://github.com/ISISComputingGroup/ibex_gui/pull/851

Ticket 3964 - Modified RATE record for HIGH interest and 2dp Prec

---

IPS/IPS-IOC-01App/Db/ips.db

Add "user" field PVs which track either the PSU field or the persistent field depending on the state of the switch heater
https://github.com/ISISComputingGroup/IBEX/issues/3995
- When the switch heater is off, persistent field is reported
- Otherwise, PSU field is reported
---

Ticket3995

---

DH2000/iocBoot/iocDH2000-IOC-01/st-common.cmd

Support second shutter, tidy up pvs, and fix various other issues - see other PRs associated with ticket
See ISISComputingGroup/IBEX#4161
* Able to control and monitor second shutter
---

Update DH2000 for second shutter

---

ROTSC/ROTSC-IOC-01App/src/build.mak
ROTSC/configure/RELEASE
ROTSC/iocBoot/iocROTSC-IOC-01/st.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/4028

Ticket4028 dropped sample

---

KNR1050/iocBoot/iocKNR1050-IOC-01/st-common.cmd

Included error setting db load

Ticket 4004: Knauer 1050 Update

---

JULABO/iocBoot/iocJULABO-IOC-01/config.xml

Description of Julabo should mention oil bath version.
https://github.com/ISISComputingGroup/IBEX/issues/3901
1. Description includes oil bath
---

Update description to include oil bath

---

TPG26x/iocBoot/iocTPG26x-IOC-01/st-common.cmd
TPG36x/Makefile
TPG36x/TPG36x-IOC-01App/Makefile
TPG36x/TPG36x-IOC-01App/src/Makefile
TPG36x/TPG36x-IOC-01App/src/TPG36x-IOC-01Main.cpp
TPG36x/TPG36x-IOC-01App/src/build.mak
TPG36x/TPG36x-IOC-02App/Makefile
TPG36x/TPG36x-IOC-02App/src/Makefile
TPG36x/TPG36x-IOC-02App/src/TPG36x-IOC-02Main.cpp
TPG36x/configure/CONFIG
TPG36x/configure/CONFIG_SITE
TPG36x/configure/Makefile
TPG36x/configure/RELEASE
TPG36x/configure/RULES
TPG36x/configure/RULES.ioc
TPG36x/configure/RULES_DIRS
TPG36x/configure/RULES_TOP
TPG36x/iocBoot/Makefile
TPG36x/iocBoot/iocTPG36x-IOC-01/Makefile
TPG36x/iocBoot/iocTPG36x-IOC-01/config.xml
TPG36x/iocBoot/iocTPG36x-IOC-01/st-common.cmd
TPG36x/iocBoot/iocTPG36x-IOC-01/st.cmd
TPG36x/iocBoot/iocTPG36x-IOC-02/Makefile
TPG36x/iocBoot/iocTPG36x-IOC-02/config.xml
TPG36x/iocBoot/iocTPG36x-IOC-02/st.cmd

Adds TPG36x IOC
https://github.com/ISISComputingGroup/IBEX/issues/3484
---

Ticket3484 support for tpg36x

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_8500_status.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_polarity.db
DFKPS/DFKPS-IOC-01App/Db/Makefile
DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml
DFKPS/iocBoot/iocDFKPS-IOC-01/st-8500.cmd

Adds status records for the danfysik 8500.
https://github.com/ISISComputingGroup/IBEX/issues/3720
---

Ticket3720 dfkps 8500

---

INHIBITR/INHIBITR-IOC-01App/src/inhibitor.st

Move function definition to bottom of file for seq 2.2
See ISISComputingGroup/IBEX#4229
* IOC compiles with seq 2.2
* IOC still functions OK
---

Move function definition

---

MEZFLIPR/iocBoot/iocMEZFLIPR-IOC-01/st-common.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/4380
* Run IOC not in any sim mode and confirm it tries to connect to a real device
N/A
---

Ticket 4380: Fix spin flipper connection

---

RKNPS/RKNPS-IOC-01App/Db/DFKPS_RIKEN.db
RKNPS/RKNPS-IOC-01App/Db/DFKPS_RIKEN_STATUS.db

Fix test
https://github.com/ISISComputingGroup/IBEX/issues/4325
1. Riken changeover tests pass
---

Ticket4325 fix tests

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/liveview.cmd
ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/4496

Move max array bytes earlier

---

ATTOCUBE/ATTOCUBE-IOC-01App/src/build.mak

Reorder libraries for linux static build (forgot to do it here too when fixed support)
Static linux build works
---

Reorder libraries for linux static build

---

ATTOCUBE/ATTOCUBE-IOC-01App/src/build.mak

Move lua library to before asyn library

Move lua to before asyn for static linux link

---

HELIOX/HELIOX-IOC-01App/src/build.mak
HELIOX/configure/RELEASE
HELIOX/iocBoot/iocHELIOX-IOC-01/config.xml
HELIOX/iocBoot/iocHELIOX-IOC-01/st-common.cmd
RUNCTRL/configure/RELEASE

Modifications to allow macros to be passed through for channel names and to depend on GSL
https://github.com/ISISComputingGroup/IBEX/issues/4549
Builds
---

Ticket4549 heliox regen

---

Makefile

Fixes build by disabling twincat

Don't build twincat unless env var set

---

TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.cmd

Added correct PV prefix for Twincat IOC, see https://github.com/ISISComputingGroup/IBEX/issues/4636
Run the IOC and confirm the PVs have the standard prefix for this IOC
---

Ticket 4636: Specified PV prefix for Twincat

---

MKSPR4KB/MKSPR4KB-IOC-01App/Makefile
MKSPR4KB/MKSPR4KB-IOC-01App/src/MKSPR4KB-IOC-01Main.cpp
MKSPR4KB/MKSPR4KB-IOC-01App/src/Makefile
MKSPR4KB/MKSPR4KB-IOC-01App/src/build.mak
MKSPR4KB/MKSPR4KB-IOC-02App/Makefile
MKSPR4KB/MKSPR4KB-IOC-02App/src/MKSPR4KB-IOC-02Main.cpp
MKSPR4KB/MKSPR4KB-IOC-02App/src/Makefile
MKSPR4KB/Makefile
MKSPR4KB/configure/CONFIG
MKSPR4KB/configure/CONFIG_SITE
MKSPR4KB/configure/Makefile
MKSPR4KB/configure/RELEASE
MKSPR4KB/configure/RULES
MKSPR4KB/configure/RULES.ioc
MKSPR4KB/configure/RULES_DIRS
MKSPR4KB/configure/RULES_TOP
MKSPR4KB/iocBoot/Makefile
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-01/Makefile
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-01/config.xml
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-01/st-common.cmd
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-01/st.cmd
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-02/Makefile
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-02/config.xml
MKSPR4KB/iocBoot/iocMKSPR4KB-IOC-02/st.cmd

Adds an IOC for MKS PR4000B controller
ISISComputingGroup/IBEX#4056
Works
---

Ticket4056 mks pr4000b

---

Makefile

Fix build, add MKSPR4KB directory

---

HELIOX/HELIOX-IOC-01App/src/build.mak
HELIOX/configure/RELEASE

Fix dbd name

---

EUROTHRM/EUROTHRM-IOC-01App/Db/devEurothrm.db

See https://github.com/ISISComputingGroup/IBEX/issues/4758
* Rebuild IOC
* Run IOC with the following macros in globals.txt: 
```
EUROTHRM_01__RECSIM=yes 
EUROTHRM_01__ADDR_1=01
```
* Confirm that P/I/D appear under HIGH in the GUI
---

Ticket 4758: Changed PID to be high interest

---

LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd

- added required devsim aysn entries
[#4665](https://github.com/ISISComputingGroup/IBEX/issues/4665)
---

Ticket 4665 - add linmot emulator

---

Makefile

Add cryosms to top level make

---

CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/config.xml
CRYOSMS/iocBoot/iocCRYOSMS-IOC-01/st-common.cmd

Reverts ISISComputingGroup/EPICS-ioc#437

Revert "Ticket4831 cryosms simple start"

---

CRYVALVE/CRYVALVE-IOC-01App/Db/CRYVALVE.db

See https://github.com/ISISComputingGroup/IBEX/issues/5028
* Run `make iocstartups`
* Start a cryovalve IOC
* Confirm there is an entry in the alarm view
---

Ticket 5028: Added alarm for cryovalve

---

ZFMAGFLD/ZFMAGFLD-IOC-01App/src/build.mak

Add missing GSL library to link

Add missing gsl library

---

ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml

Make macros more permissive

---

ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd

Changes DAQ acquisition to faster mode
---

Use monster mode for higher data rates

---

INSTETC/iocBoot/iocINSTETC-IOC-01/st.cmd

Load dashboard PVs from config area into INSTETC
https://github.com/ISISComputingGroup/IBEX/issues/5014
- PVs are loaded appropriately
---

Load dashboard PVs from config area

---

ITC503/ITC503-IOC-01App/Db/ITC503.db

See https://github.com/ISISComputingGroup/IBEX/issues/5125

Allow setting max voltage

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/dllPath_extra.bat

Add visa path if not present locally
See ISISComputingGroup/IBEX#5134
VISA set in path if not present locallly
---

Load VISA locally if not present on system

---

ROTSC/ROTSC-IOC-01App/src/build.mak
SPRLG/SPRLG-IOC-01App/src/build.mak

Adjust library order for linux static build
See ISISComputingGroup/IBEX#5281
* linux static build succeeds 
---

Fix linux static build

---

Makefile

Add missing lSI Correlatormake

Correct make file to include LSICORR

---

IPS/IPS-IOC-01App/Db/ips.db

Remove space character which now breaks protocol
See ISISComputingGroup/IBEX#5357
IPS starts without error listed on above ticket
---

Remove space breaking protocol

---

KHLY2700/KHLY2700-IOC-01App/Db/keithley2700.db

Removes a processing loop
https://github.com/ISISComputingGroup/IBEX/issues/5382
IOC no longer stops updating certain PVs after ~1 day of usage.
---

process loop removed in KHLY2700

---

ROTSC/ROTSC-IOC-01App/src/build.mak
ROTSC/configure/RELEASE
ROTSC/iocBoot/iocROTSC-IOC-01/st.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/4287
See https://github.com/ISISComputingGroup/EPICS-rotating_sample_changer/pull/6
---

Ticket 4287: Update ROTSC from tests

---

OERCONE/iocBoot/iocOERCONE-IOC-01/st-common.lua
TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua

See ticket at https://github.com/ISISComputingGroup/IBEX/issues/5381. Fix is detailed in documentation at https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Lua
* Confirm the error in the original ticket no longer occurs
---

Ticket 5381: Updated lua scripts to correctly scope imports

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_calibrated.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_common.db
DFKPS/DFKPS-IOC-01App/Db/DFKPS_polarity.db

Add archiving
https://github.com/ISISComputingGroup/IBEX/issues/5216
Extra diagnostic info archived
---

Add additional archiving

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/liveview.cmd

Fix issues with latest areaDetector (see ticket)
See ISISComputingGroup/IBEX#5467
* no errors on load and liveview works
---

Fix issues with new recent areaDetector

---

MERCURY_ITC/MERCURY-IOC-01App/src/build.mak
MERCURY_ITC/configure/RELEASE
MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml

https://github.com/ISISComputingGroup/IBEX/issues/1392
Equivalent functionality to old lvdcom ioc / labview driver
---

Ticket1392 mercury epics ioc

---

FINS/FINS-IOC-01App/Db/sans2d-vac-status.template

Added binary record to tell us if a vessel is under vacuum
---

Binary record to tell us if vessel is under vacuum

---

Makefile

Add galilmul to top level makefile

---

ISISDAE/ISISDAE-IOC-01App/src/build.mak
NGEM/NGEM-IOC-01App/src/build.mak

Fix Kakfa element of build on linux/VS2010

Fix vs2010 and linux builds

---

INHIBITR/INHIBITR-IOC-01App/src/inhibitor.st

Remove extra SYNC argument which is only required by `pvPut` (the underlying function) but not `PVPUT` (the function-like macro).
https://github.com/ISISComputingGroup/IBEX/issues/5670
Build works without warnings/errors
---

Remove SYNC (required by pvPut, not requried by PVPUT)

---

ITC503/ITC503-IOC-01App/Db/ITC503.db

Add missing :SP aliases
See ISISComputingGroup/IBEX#5782
settemp() on EMU does not error when setting the cycle block 
---

Add missing records

---

CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd

Force load defaults settings rather than use autosave
See ISISComputingGroup/IBEX#5624
---

Force load defaults on startup

---

DFKPS/iocBoot/iocDFKPS-IOC-01/config.xml

Make macro description clearer
https://github.com/ISISComputingGroup/IBEX/issues/5844
Description is better
---

Add better message

---

Makefile
SMRTMON/Makefile
SMRTMON/SMRTMON-IOC-01App/Db/Makefile
SMRTMON/SMRTMON-IOC-01App/Makefile
SMRTMON/SMRTMON-IOC-01App/protocol/Makefile
SMRTMON/SMRTMON-IOC-01App/src/Makefile
SMRTMON/SMRTMON-IOC-01App/src/SMRTMON-IOC-01Main.cpp
SMRTMON/SMRTMON-IOC-01App/src/build.mak
SMRTMON/configure/CONFIG
SMRTMON/configure/CONFIG_SITE
SMRTMON/configure/Makefile
SMRTMON/configure/RELEASE
SMRTMON/configure/RULES
SMRTMON/configure/RULES.ioc
SMRTMON/configure/RULES_DIRS
SMRTMON/configure/RULES_TOP
SMRTMON/iocBoot/Makefile
SMRTMON/iocBoot/iocSMRTMON-IOC-01/Makefile
SMRTMON/iocBoot/iocSMRTMON-IOC-01/config.xml
SMRTMON/iocBoot/iocSMRTMON-IOC-01/st-common.cmd
SMRTMON/iocBoot/iocSMRTMON-IOC-01/st.cmd

Adds an IOC for the HTS Magnet SmartMonitor
ISISComputingGroup/IBEX#5663
See Issue
---

Ticket5663: HTS Smart Monitor

---

FINS/FINS-IOC-01App/Db/larmor-air-header.template

Remove invalid characters

---

FZJDDFCH/FZJDDFCH-IOC-01App/Db/FZJDDFCH.db

remove degrees symbol

---

ILM200/ILM200-IOC-01App/Db/ILM200_channel.db
ILM200/iocBoot/iocILM200-IOC-01/config.xml
ILM200/iocBoot/iocILM200-IOC-01/st-common.cmd

https://github.com/ISISComputingGroup/IBEX/issues/5839
---

Add ability to specify alarm thresholds

---

Makefile
PT2025/Makefile
PT2025/PT2025-IOC-01App/Db/Makefile
PT2025/PT2025-IOC-01App/Makefile
PT2025/PT2025-IOC-01App/src/Makefile
PT2025/PT2025-IOC-01App/src/PT2025-IOC-01Main.cpp
PT2025/PT2025-IOC-01App/src/build.mak
PT2025/PT2025-IOC-02App/Db/Makefile
PT2025/PT2025-IOC-02App/Makefile
PT2025/PT2025-IOC-02App/src/Makefile
PT2025/PT2025-IOC-02App/src/PT2025-IOC-02Main.cpp
PT2025/configure/CONFIG
PT2025/configure/CONFIG_SITE
PT2025/configure/Makefile
PT2025/configure/RELEASE
PT2025/configure/RULES
PT2025/configure/RULES.ioc
PT2025/configure/RULES_DIRS
PT2025/configure/RULES_TOP
PT2025/iocBoot/Makefile
PT2025/iocBoot/iocPT2025-IOC-01/Makefile
PT2025/iocBoot/iocPT2025-IOC-01/config.xml
PT2025/iocBoot/iocPT2025-IOC-01/st-common.cmd
PT2025/iocBoot/iocPT2025-IOC-01/st.cmd
PT2025/iocBoot/iocPT2025-IOC-02/Makefile
PT2025/iocBoot/iocPT2025-IOC-02/config.xml
PT2025/iocBoot/iocPT2025-IOC-02/st.cmd

PT2025 IOC
https://github.com/ISISComputingGroup/EPICS
- PT2025 IOC can ready I/Os
---

Ticket5029 pt2025 support

---

PT2025/iocBoot/iocPT2025-IOC-01/config.xml

Fix build:
See also:
1. https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/399
2. https://github.com/ISISComputingGroup/EPICS-pt2025/pull/2
N/A
Build works
---

Add missing macros

---

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db

Removes duplicate SIM record
---

Remove unnecessary record

---

.gitignore

Update gitignore to include specific dllPath architectures. See https://github.com/ISISComputingGroup/IBEX/issues/5926
* Pull and make epics base
* make an IOC
* Run `git status` and confirm the architecture specific dllPath is not being tracked 
---

Ticket 5926: Update .gitignore

---

CAENV895/iocBoot/iocCAENV895-IOC-01/st-common.cmd

Add macros for running tests
See https://github.com/ISISComputingGroup/IBEX/issues/4915
IOC tests run
---

Ticket4915 add tests

---

FMR/FMR-IOC-01App/Makefile
FMR/FMR-IOC-01App/src/FMR-IOC-01Main.cpp
FMR/FMR-IOC-01App/src/Makefile
FMR/FMR-IOC-01App/src/build.mak
FMR/Makefile
FMR/configure/CONFIG
FMR/configure/CONFIG_SITE
FMR/configure/Makefile
FMR/configure/RELEASE
FMR/configure/RULES
FMR/configure/RULES.ioc
FMR/configure/RULES_DIRS
FMR/configure/RULES_TOP
FMR/iocBoot/Makefile
FMR/iocBoot/iocFMR-IOC-01/Makefile
FMR/iocBoot/iocFMR-IOC-01/config.xml
FMR/iocBoot/iocFMR-IOC-01/st.cmd

LVDCOM IOC to wrap users' VI
See [ticket](https://github.com/ISISComputingGroup/IBEX/issues/5270)
Details on ticket
---

Ticket5270 fmr

---

Makefile

Add FMR to makefiel so it builds
-
-
---

Add FMR to makefile

---

TTIEX355P/TTIEX355P-IOC-01App/Db/ttiEX355P.db
TTIEX355P/TTIEX355P-IOC-01App/src/build.mak
TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/config.xml
TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/st.cmd

https://github.com/ISISComputingGroup/IBEX/issues/5099
---

Add functionality for MuSR

---

ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml
ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st-daq.cmd
ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/st.cmd

https://github.com/ISISComputingGroup/IBEX/issues/5096
---

Add spare daq channel

---

TTIEX355P/iocBoot/iocTTIEX355P-IOC-01/config.xml

Remove stray commas from config xml

Remove stray commas

---

RUNCTRL/RUNCTRL_01App/Db/runcontrol.substitutions
RUNCTRL/iocBoot/iocRUNCTRL_01/st.cmd

Add options to control alias generation with run control IOC rather than blockserver
See ISISComputingGroup/IBEX#5925
* DB files loaded without error
* run control works as before
---

Control alias generation

---

HVCAENA/HVCAENA-IOC-01App/src/build.mak
Makefile

Fix CAEN static build, and exclude building on VS2010

Fix caen static

---

KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml

See https://github.com/ISISComputingGroup/IBEX/issues/6151
---

Ticket 6151: Clarify the max current is also negative

---

HVCAEN/HVCAEN-IOC-01App/src/build.mak
HVCAEN/HVCAENSIM-IOC-01App/src/build.mak

Remove old library to fix linux build

Remove no longer needed library for HVCAEN

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_calibrated.db

Remove duplicate alias in calibration db file

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_slew.db

adding scan for slew rate rbvs

---

HLX503/HLX503-IOC-01App/src/build.mak

Adjust library order

---

MCLEN/iocBoot/iocMCLEN-IOC-01/config.xml

See https://github.com/ISISComputingGroup/IBEX/issues/5729
Note, was originally done in https://github.com/ISISComputingGroup/EPICS-ioc/pull/597 but that PR contains so extra stuff
---

Ticket5729: Add homing mode to config xml

---

HLX503/iocBoot/iocHLX503-IOC-01/config.xml

fix missing xml tag for hlx503

---

KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/6350 and https://github.com/ISISComputingGroup/EPICS-ReadASCII/pull/12.
---

Ticket 6350: Reduce readASCII logging on the kepco

---

HIFIMAGS/HIFIMAGS-IOC-01App/Db/switching.db

https://github.com/ISISComputingGroup/IBEX/issues/6221
---

Correct units

---

KEPCO/iocBoot/iocKEPCO-IOC-01/config.xml
KEPCO/iocBoot/iocKEPCO-IOC-01/st-common.cmd

adding AUTOSAVE_CURRENT macro to kepco

---

ILM200/iocBoot/iocILM200-IOC-01/config.xml
ILM200/iocBoot/iocILM200-IOC-01/st-common.cmd

ILM200: 
- Add @ in ILM200 Isobus address to account for new protocol
- Add macro to control whether to use Isobus or not
https://github.com/ISISComputingGroup/IBEX/issues/6328
---

ILM200 new protocol change

---

SMTOF70/iocBoot/iocSMTOF70-IOC-02/config.xml

Adds a second config.xml which references the first IOCs config.xml
Confirm that `make iocstartups`  no longer errors. 
---

Flash tof70 configxml

---

LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd

Allows LINMOT settings directory to be set from a macro, required to test https://github.com/ISISComputingGroup/IBEX/issues/6423
---

Ticket 6423: Added macro to set where linmot gets its settings from

---

JULABO/JULABO-IOC-01App/Db/julabo.db

Archive Julabo circulating mode

Archive mode

---

DFKPS/iocBoot/iocDFKPS-IOC-01/st-common.cmd

Change path separator for new version of stream device 
See ISISComputingGroup/IBEX#6596
---

Change path separator

---

DFKPS/DFKPS-IOC-01App/Db/DFKPS_slew.db

adding units to slew pvs

---

HIFIMAGS/HIFIMAGS-IOC-01App/src/hifimagsys.st

See ticket https://github.com/ISISComputingGroup/IBEX/issues/6744
---

Fix hifimags tests

---

KHLY2700/KHLY2700-IOC-01App/Db/keithley2700.db

Improve parsing logic
See ISISComputingGroup/IBEX#6827
---

Improve processing of values

---

TWINCAT/TWINCAT-IOC-01App/Db/single_axis.substitutions

Ticket6856

---

GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd
TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua

Publish number of axes for motor IOCs

---

TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.cmd

We should load these in so that when we replace a sample changer it should be plug-and-play from a Galil-Beckhoff. The .cmd files are all made to be controller-agnostic and work off the motor record so should all still work. 
we do this already for the Galil for example: https://github.com/ISISComputingGroup/EPICS-ioc/blob/465ad9fd3bf492c74349d8c7d618c41216155f5a/GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd#L72-L88
Load in each of the .cmd files and test, though this step is probably not needed as they work with Galils etc.
---
- [Record …

Add in Barndoors, sample changer and motor extensions to TWINCAT IOC

---

TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.cmd

See https://github.com/ISISComputingGroup/IBEX/issues/6823
---

Ticket 6823: Add twincat to motors moving and stop all

---

PEARLPC/README.md

Add minimum documentation to PEARLPC README.md to get developers up and running quickly
---

Create README.md with minimum documentation

---

ISISDAE/iocBoot/iocISISDAE-IOC-01/st.cmd
ISISDAE/postbuild/update_dlls.bat

See ISISComputingGroup/IBEX#6949

Remove isisicpint/nodcom option

---

TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua

alias overflowed records to the next motor controller

---

TWINCAT/iocBoot/iocTWINCAT-IOC-01/st-common.lua

upping tcioc scan rate - this solves the early DMOV problem

---

RUNCTRL/RUNCTRL_01App/Db/runcontrol.substitutions
RUNCTRL/iocBoot/iocRUNCTRL_01/st.cmd

Add NOARCHIVE option

---

TC/iocBoot/iocTC-IOC-01/st-common.lua

revert scan rate

---

GAMRY/iocBoot/iocGAMRY-IOC-01/config.xml
HVCAENA/iocBoot/iocHVCAENA-IOC-01/config.xml
HVCAENA/iocBoot/iocHVCAENA-IOC-02/config.xml
HVCAENA/iocBoot/iocHVCAENA-IOC-03/config.xml
HVCAENA/iocBoot/iocHVCAENA-IOC-04/config.xml
KYNCTM3K/iocBoot/iocKYNCTM3K-IOC-01/config.xml
NANODAC/iocBoot/iocNANODAC-IOC-01/config.xml
NGPSPSU/iocBoot/iocNGPSPSU-IOC-01/config.xml
QEPRO/iocBoot/iocQEPRO-IOC-01/config.xml
QEPRO/iocBoot/iocQEPRO-IOC-02/config.xml
SECI2IBEX/iocBoot/iocSECI2IBEX-IOC-01/config.xml
SP2XX/iocBoot/iocSP2XX-IOC-01/config.xml
TIZR/iocBoot/iocTIZR-IOC-01/config.xml

Changed descriptions of some IOCs to be better used as the top level of the new treeview
Check the new names make sense
https://github.com/ISISComputingGroup/IBEX/issues/7013
---

Changed Non-human readable or non sensible descriptions

---

INSTETC/INSTETC-IOC-01App/Db/INSTETC.db

See https://github.com/ISISComputingGroup/IBEX/issues/5238
---

Ticket 5238: Add a PV for storing the perspectives to show

---

Makefile
WEBCAM/Makefile
WEBCAM/WEBCAM-IOC-01App/Db/Makefile
WEBCAM/WEBCAM-IOC-01App/Makefile
WEBCAM/WEBCAM-IOC-01App/protocol/Makefile
WEBCAM/WEBCAM-IOC-01App/src/Makefile
WEBCAM/WEBCAM-IOC-01App/src/WEBCAM-IOC-01Main.cpp
WEBCAM/WEBCAM-IOC-01App/src/build.mak
WEBCAM/configure/CONFIG
WEBCAM/configure/CONFIG_SITE
WEBCAM/configure/Makefile
WEBCAM/configure/RELEASE
WEBCAM/configure/RULES
WEBCAM/configure/RULES.ioc
WEBCAM/configure/RULES_DIRS
WEBCAM/configure/RULES_TOP
WEBCAM/iocBoot/Makefile
WEBCAM/iocBoot/iocWEBCAM-IOC-01/Makefile
WEBCAM/iocBoot/iocWEBCAM-IOC-01/config.xml
WEBCAM/iocBoot/iocWEBCAM-IOC-01/st-common.cmd
WEBCAM/iocBoot/iocWEBCAM-IOC-01/st.cmd

Add webcam ioc

---

WEBCAM/iocBoot/iocWEBCAM-IOC-01/WEBCAM_01_settings.req
WEBCAM/iocBoot/iocWEBCAM-IOC-01/config.xml
WEBCAM/iocBoot/iocWEBCAM-IOC-01/st-common.cmd

Add IOC to read webcam images using epics areaDetector
See ISISComputingGroup/IBEX#7146
IOC displays webcam in OPI (see associated GUI ticket)
---

Configure webcam

---

HLX503/iocBoot/iocHLX503-IOC-01/config.xml
HLX503/iocBoot/iocHLX503-IOC-01/st-common.cmd

Field test fixes

---

TECHNIX/iocBoot/iocTECHNIX-IOC-01/config.xml

add hasDefault=NO to technix ioc

---

PEARLPC/iocBoot/iocPEARLPC-IOC-01/st-common.cmd

Pass `$(P)` in the standard ISIS format to reduce duplication in the DB.
https://github.com/ISISComputingGroup/IBEX/issues/6770
---

Pass macro to reduce duplication in DB

---

PEARLPC/iocBoot/iocPEARLPC-IOC-01/config.xml
PEARLPC/iocBoot/iocPEARLPC-IOC-01/st-common.cmd

Add macros
See ISISComputingGroup/IBEX#7193
---

Add macros

---

FMR/iocBoot/iocFMR-IOC-01/config.xml
FMR/iocBoot/iocFMR-IOC-01/st.cmd

add VNASTAND macro to allow controlling VNA on its own

---

HUBER/iocBoot/iocHUBER-IOC-01/config.xml
HUBER/iocBoot/iocHUBER-IOC-01/st-motor.cmd

Updated macros and st.cmd for huber to work over serial
https://github.com/ISISComputingGroup/IBEX/issues/7166
---

Ticket7166 changes nessecary to run huber on hardware

---

TECHNIX/iocBoot/iocTECHNIX-IOC-01/config.xml

https://github.com/ISISComputingGroup/IBEX/issues/7129
See ticket
---

Allow floating-point numbers in macro pattern

---

Makefile
TJMPER/Makefile
TJMPER/TJMPER-IOC-01App/Db/Makefile
TJMPER/TJMPER-IOC-01App/Db/tjmper.substitutions
TJMPER/TJMPER-IOC-01App/Makefile
TJMPER/TJMPER-IOC-01App/src/Makefile
TJMPER/TJMPER-IOC-01App/src/TJMPER-IOC-01Main.cpp
TJMPER/TJMPER-IOC-01App/src/build.mak
TJMPER/configure/CONFIG
TJMPER/configure/CONFIG_SITE
TJMPER/configure/Makefile
TJMPER/configure/RELEASE
TJMPER/configure/RULES
TJMPER/configure/RULES.ioc
TJMPER/configure/RULES_DIRS
TJMPER/configure/RULES_TOP
TJMPER/iocBoot/Makefile
TJMPER/iocBoot/iocTJMPER-IOC-01/Makefile
TJMPER/iocBoot/iocTJMPER-IOC-01/config.xml
TJMPER/iocBoot/iocTJMPER-IOC-01/st-common.cmd
TJMPER/iocBoot/iocTJMPER-IOC-01/st.cmd

Added the TJMPER IOC.
See https://github.com/ISISComputingGroup/IBEX/issues/7253.
See ticket.
---

Ticket7253 tjmper phase 1

---

B17TMAG/iocBoot/iocB17TMAG-IOC-01/config.xml
TJMPER/iocBoot/iocTJMPER-IOC-01/config.xml

Added 'hasDefault' to config.xml to fix iocstartups warnings.

---

BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/config.xml
BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/dllPath.bat
BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-01/runIOC.bat
BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-02/dllPath.bat
BGRSCRPT/iocBoot/iocBGRSCRPT-IOC-02/runIOC.bat
BGRSCRPT/settings/bgrscrpt_script.py

Added a path macro to the Background Script IOC.
https://github.com/ISISComputingGroup/IBEX/issues/5743
See ticket.
---

Added script path macro to the Background Script IOC.

---

LKSH336/LKSH336-IOC-01App/Db/lakeshore336.substitutions

Added substitutions to Lakeshore336 for loop/output 3 and 4 support.
See https://github.com/ISISComputingGroup/IBEX/issues/7261
See ticket.
---

Ticket7261 lksh336 4 loops

---

TC/TC-IOC-01App/src/build.mak
TC/configure/RELEASE

Add motionsetpoints into CONFIGURE/RELEASE for TC

---

JSCO4180/JSCO4180-IOC-02App/Db/Makefile
JSCO4180/JSCO4180-IOC-02App/Makefile
JSCO4180/JSCO4180-IOC-02App/src/JSCO4180-IOC-02Main.cpp
JSCO4180/JSCO4180-IOC-02App/src/Makefile
JSCO4180/JSCO4180-IOC-03App/Db/Makefile
JSCO4180/JSCO4180-IOC-03App/Makefile
JSCO4180/JSCO4180-IOC-03App/src/JSCO4180-IOC-03Main.cpp
JSCO4180/JSCO4180-IOC-03App/src/Makefile
JSCO4180/iocBoot/iocJSCO4180-IOC-02/Makefile
JSCO4180/iocBoot/iocJSCO4180-IOC-02/config.xml
JSCO4180/iocBoot/iocJSCO4180-IOC-02/st.cmd
JSCO4180/iocBoot/iocJSCO4180-IOC-03/Makefile
JSCO4180/iocBoot/iocJSCO4180-IOC-03/config.xml
JSCO4180/iocBoot/iocJSCO4180-IOC-03/st.cmd

Added JSCO4180 IOC 2 and 3.
https://github.com/ISISComputingGroup/IBEX/issues/4318
See ticket.
---

Ticket4318

---

TC/TC-IOC-01App/Db/axis_monitors.db

Ticket7283

---

LKSH336/LKSH336-IOC-01App/Db/lakeshore336.substitutions

[Ticket #7343](https://github.com/ISISComputingGroup/IBEX/issues/7343)
Added a `CMD` param so can use different commands to retrieve output for different channel types in the same PV.
---

Ticket 7343

---

Makefile

I forgot to add the new `INSTRONA` ioc to the makefile.

Add instrona to makefile

---

TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st-common.cmd

* Remove duplicate include of dbload.cmd
* Add SCAN macro
See ISISComputingGroup/IBEX#7352
Load DB correctly as before
---

TEKAFG3XXX: Remove duplicate dbload, add SCAN macro

---

FINS/exampleSettings/ZOOM_vacuum/FINS_01.cmd

Added FINS settings for Zoom for the system tests for `do_sans` `do_trans` instrument scripts. 
https://github.com/ISISComputingGroup/IBEX/issues/7132
See: https://github.com/ISISComputingGroup/system_tests/pull/89
---

Added example settings for zoom FINS for system tests

---

TC/iocBoot/iocTC-IOC-01/st-common.lua

match comment to scan rate

---

TC/TC-IOC-01App/src/build.mak

add asub to build.mak for TC

---

MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/st-temp-spc.cmd

Fix as the dev machines can use the instrument name as it's the same as the host. This is different on the NDXs 
Fixes ISISComputingGroup/IBEX#7415
---

Fix macro being wrong for lookup file directory

---

TJMPAP/TJMPAP-IOC-01App/src/build.mak

Fix static build

---

FINS/FINS-IOC-01App/Db/zoom-vacuum-commands.template
FINS/FINS-IOC-01App/Db/zoom-vacuum.substitutions

Added SIM records for zoom vacuum commands.

---

DG645/iocBoot/iocDG645-IOC-01/st-common.cmd

Added output channel GH.
https://github.com/ISISComputingGroup/IBEX/issues/7367
See ticket.
---

Ticket7376

---

GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-common.cmd
LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd

Add macro to control whether to autosave jaws positions
See ISISComputingGroup/IBEX#7234
---

Add macro to control jaws autosave SP

---

MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml
MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd

Add `BOOSTER_TYPE` PV (requested by EMU inst. sci.)

Add booster_Type pv

---

IPS/IPS-IOC-01App/Db/ips.db
IPS/IPS-IOC-01App/src/cryomagnet.st

https://github.com/ISISComputingGroup/IBEX/issues/4224

Mercury IPS mods

---

GALIL/GALIL-IOC-01App/Db/galil_motor_extras.substitutions

Add IOCNAME macro.

---

SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE.substitutions
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Pumpset_Summary.template

Added Summary PVs for use with the Vacuum Synoptic OPI
https://github.com/ISISComputingGroup/IBEX/issues/5878
The Summary PVs properly display if any of the fields they summarise are fault or disconnected
---

Changes to RIKEN SCHNEIDER template to add summary PVs for OPI

---

FINS/FINS-IOC-01App/Db/Makefile
FINS/FINS-IOC-01App/Db/sandals-base.template
FINS/FINS-IOC-01App/Db/sandals-gate-valve-single.template
FINS/FINS-IOC-01App/Db/sandals-gate-valve.substitutions
FINS/exampleSettings/SANDALS_gate_valve/FINS_01.cmd

Ticket7543 sandals gate valve

---

KHLY2000/KHLY2000-IOC-01App/Makefile
KHLY2000/KHLY2000-IOC-01App/src/KHLY2000-IOC-01Main.cpp
KHLY2000/KHLY2000-IOC-01App/src/Makefile
KHLY2000/KHLY2000-IOC-01App/src/build.mak
KHLY2000/KHLY2000-IOC-02App/Makefile
KHLY2000/KHLY2000-IOC-02App/src/KHLY2000-IOC-02Main.cpp
KHLY2000/KHLY2000-IOC-02App/src/Makefile
KHLY2000/Makefile
KHLY2000/configure/CONFIG
KHLY2000/configure/CONFIG_SITE
KHLY2000/configure/Makefile
KHLY2000/configure/RELEASE
KHLY2000/configure/RULES
KHLY2000/configure/RULES.ioc
KHLY2000/configure/RULES_DIRS
KHLY2000/configure/RULES_TOP
KHLY2000/iocBoot/Makefile
KHLY2000/iocBoot/iocKHLY2000-IOC-01/Makefile
KHLY2000/iocBoot/iocKHLY2000-IOC-01/config.xml
KHLY2000/iocBoot/iocKHLY2000-IOC-01/st-common.cmd
KHLY2000/iocBoot/iocKHLY2000-IOC-01/st.cmd
KHLY2000/iocBoot/iocKHLY2000-IOC-02/Makefile
KHLY2000/iocBoot/iocKHLY2000-IOC-02/config.xml
KHLY2000/iocBoot/iocKHLY2000-IOC-02/st.cmd
Makefile

https://github.com/ISISComputingGroup/IBEX/issues/2460

Add Keithley 2000

---

SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_BeamBlocker_Information.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Common_Objects_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Integer.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Kicker_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_PIV_Interlock_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_RBox_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Solenoid_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Vacuum_Pump_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Vacuum_Valve_Interlock_Status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_Vacuum_Valve_Open.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_float.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_other_objects_status.template
SCHNDR/SCHNDR-IOC-01App/Db/RIKENFE_vacuum_valve_status.template

Added to reduce logging rate and therefor disk usage
None
Logging rate reduced to once per 10 seconds per PV
---

Add log per 10 second to archive fields

---

KSE4980/KSE4980-IOC-01App/Db/Makefile
KSE4980/KSE4980-IOC-01App/Makefile
KSE4980/KSE4980-IOC-01App/src/KSE4980-IOC-01Main.cpp
KSE4980/KSE4980-IOC-01App/src/Makefile
KSE4980/KSE4980-IOC-01App/src/build.mak
KSE4980/KSE4980-IOC-02App/Db/Makefile
KSE4980/KSE4980-IOC-02App/Makefile
KSE4980/KSE4980-IOC-02App/src/KSE4980-IOC-02Main.cpp
KSE4980/KSE4980-IOC-02App/src/Makefile
KSE4980/Makefile
KSE4980/configure/CONFIG
KSE4980/configure/CONFIG_SITE
KSE4980/configure/Makefile
KSE4980/configure/RELEASE
KSE4980/configure/RULES
KSE4980/configure/RULES.ioc
KSE4980/configure/RULES_DIRS
KSE4980/configure/RULES_TOP
KSE4980/iocBoot/Makefile
KSE4980/iocBoot/iocKSE4980-IOC-01/Makefile
KSE4980/iocBoot/iocKSE4980-IOC-01/config.xml
KSE4980/iocBoot/iocKSE4980-IOC-01/st-common.cmd
KSE4980/iocBoot/iocKSE4980-IOC-01/st.cmd
KSE4980/iocBoot/iocKSE4980-IOC-02/Makefile
KSE4980/iocBoot/iocKSE4980-IOC-02/config.xml
KSE4980/iocBoot/iocKSE4980-IOC-02/st.cmd
Makefile

Ticket7663 add ioc kse4980

---

GALIL/GALIL-IOC-01App/Db/galil_digital_ports.substitutions
GALIL/iocBoot/iocGALIL-IOC-01/galildb.cmd

Add recsim support for the input `_STATUS` Galil PV. 
[Ticket #7625](https://github.com/ISISComputingGroup/IBEX/issues/7625)
---

Add recsim for status (input) PV

---

KHLY2700/KHLY2700-IOC-01App/Db/keithley2700.db
KHLY2700/iocBoot/iocKHLY2700-IOC-01/st-common.cmd

The ioc expects 3 items per value, if max buffer size is not a multiple of 3 then when it reads a complete buffer it throws all the values away
---

Make buffer size a multiple of 3 (1000->999)

---

TC/TC-IOC-01App/Db/axis_monitors.db
TC/TC-IOC-01App/Db/single_axis_tc.db

forward jog velocity from beckhoff controller to motor record

---

Makefile
PACE5000/Makefile
PACE5000/PACE5000-IOC-01App/Db/Makefile
PACE5000/PACE5000-IOC-01App/Makefile
PACE5000/PACE5000-IOC-01App/src/Makefile
PACE5000/PACE5000-IOC-01App/src/PACE5000-IOC-01Main.cpp
PACE5000/PACE5000-IOC-01App/src/build.mak
PACE5000/configure/CONFIG
PACE5000/configure/CONFIG_SITE
PACE5000/configure/Makefile
PACE5000/configure/RELEASE
PACE5000/configure/RULES
PACE5000/configure/RULES.ioc
PACE5000/configure/RULES_DIRS
PACE5000/configure/RULES_TOP
PACE5000/iocBoot/Makefile
PACE5000/iocBoot/iocPACE5000-IOC-01/Makefile
PACE5000/iocBoot/iocPACE5000-IOC-01/config.xml
PACE5000/iocBoot/iocPACE5000-IOC-01/st-common.cmd
PACE5000/iocBoot/iocPACE5000-IOC-01/st.cmd

https://github.com/ISISComputingGroup/IBEX/issues/6044
---

Ticket6044

---

TC/TC-IOC-01App/Db/axis_monitors.db
TC/iocBoot/iocTC-IOC-01/st-common.lua

Inter additions

---

FINS/FINS-IOC-01App/Db/sandals-base.template

Ticket8000

---

TC/TC-IOC-01App/Db/axis_monitors.db

forward VMAX from VELO or else the reflectometry server complains

---

TC/TC-IOC-02App/Db/Makefile
TC/TC-IOC-02App/Makefile
TC/TC-IOC-02App/protocol/Makefile
TC/TC-IOC-02App/src/Makefile
TC/TC-IOC-02App/src/TC-IOC-02Main.cpp
TC/iocBoot/iocTC-IOC-02/Makefile
TC/iocBoot/iocTC-IOC-02/TC_02_settings.req
TC/iocBoot/iocTC-IOC-02/config.xml
TC/iocBoot/iocTC-IOC-02/st.cmd

add stuff in IOC for allowing 2 TC IOCs

---

GALIL/iocBoot/iocGALIL-IOC-01/config.xml
GALILMUL/iocBoot/iocGALILMUL-IOC-01/config.xml

Add support for COM in GALILADDR macro
See ISISComputingGroup/IBEX#8218
See ticket
---

Add supprt for COM in GALILADDR macro

---

PACE5000/iocBoot/iocPACE5000-IOC-01/config.xml
PACE5000/iocBoot/iocPACE5000-IOC-01/st-common.cmd

pace5000 snags

---

TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/config.xml
TEKAFG3XXX/iocBoot/iocTEKAFG3XXX-IOC-01/st-common.cmd

Add two macros for enabling channels individually

---

TC/iocBoot/iocTC-IOC-01/config.xml

add comment for removal of crisp jaws code

---

LNDYISW/LNDYISW-IOC-01App/src/build.mak

Add link to build.mak

---

TC/TC-IOC-01App/Db/axis_monitors.db

fix table of motors energised icon for beckhoffs

---

LVREMOTE/iocBoot/iocLVREMOTE-IOC-01/config.xml

LVRemote still had a template description in its config

remove template description

---

GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam.cmd
GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd

Ticket8345

---

ALDN1000/iocBoot/iocALDN1000-IOC-01/config.xml
ALDN1000/iocBoot/iocALDN1000-IOC-01/st-common.cmd

Support daisy chaining pumps

---

SR400/Makefile
SR400/SR400-IOC-01App/Makefile
SR400/SR400-IOC-01App/src/Makefile
SR400/SR400-IOC-01App/src/SR400-IOC-01Main.cpp
SR400/SR400-IOC-01App/src/build.mak
SR400/SR400-IOC-02App/Db/Makefile
SR400/SR400-IOC-02App/Makefile
SR400/SR400-IOC-02App/src/Makefile
SR400/SR400-IOC-02App/src/SR400-IOC-02Main.cpp
SR400/configure/CONFIG
SR400/configure/CONFIG_SITE
SR400/configure/Makefile
SR400/configure/RELEASE
SR400/configure/RULES
SR400/configure/RULES.ioc
SR400/configure/RULES_DIRS
SR400/configure/RULES_TOP
SR400/iocBoot/Makefile
SR400/iocBoot/iocSR400-IOC-01/Makefile
SR400/iocBoot/iocSR400-IOC-01/config.xml
SR400/iocBoot/iocSR400-IOC-01/st-common.cmd
SR400/iocBoot/iocSR400-IOC-01/st.cmd
SR400/iocBoot/iocSR400-IOC-02/Makefile
SR400/iocBoot/iocSR400-IOC-02/config.xml
SR400/iocBoot/iocSR400-IOC-02/st.cmd

All of the changes here were generated. No further customisation was needed.
run the IOC tests from support subdmodule.
- works
---

Add template IOC

---

TC/iocBoot/iocTC-IOC-01/st-common.cmd

sum read every 200ms rather than 1ms

---

TC/iocBoot/iocTC-IOC-01/st-common.cmd

exit if no NUM_AXES defined

---

TEKDMM40X0/TEKDMM40X0-IOC-02App/Db/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-02App/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-02App/src/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-02App/src/TEKDMM40X0-IOC-02Main.cpp
TEKDMM40X0/TEKDMM40X0-IOC-03App/Db/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-03App/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-03App/src/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-03App/src/TEKDMM40X0-IOC-03Main.cpp
TEKDMM40X0/TEKDMM40X0-IOC-04App/Db/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-04App/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-04App/src/Makefile
TEKDMM40X0/TEKDMM40X0-IOC-04App/src/TEKDMM40X0-IOC-04Main.cpp
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-02/Makefile
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-02/config.xml
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-02/st.cmd
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-03/Makefile
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-03/config.xml
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-03/st.cmd
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-04/Makefile
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-04/config.xml
TEKDMM40X0/iocBoot/iocTEKDMM40X0-IOC-04/st.cmd

duplicate tekdmm40x0 ioc and make 4 iocs - needed for CHIPIR

---

MUONTPAR/MUONTPAR-IOC-01App/src/build.mak
MUONTPAR/configure/RELEASE
MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/config.xml
MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd

Ticket6232 ability to edit tpar file within ibex

---

NCINDG/iocBoot/iocNCINDG-IOC-01/config.xml
NCINDG/iocBoot/iocNCINDG-IOC-01/st-common.cmd

Add inst sync

---

GALIL/iocBoot/iocGALIL-IOC-01/st-common.cmd
GALILMUL/iocBoot/iocGALILMUL-IOC-01/st-common.cmd
LINMOT/iocBoot/iocLINMOT-IOC-01/st-common.cmd
MCLEN/iocBoot/iocMCLEN-IOC-01/st-common.cmd
SM300/iocBoot/iocSM300-IOC-01/st-common.cmd
SMC100/iocBoot/iocSMC100-IOC-01/st-common.cmd
TC/iocBoot/iocTC-IOC-01/st-common.cmd

https://github.com/isiscomputinggroup/ibex/issues/8427

Point st.cmds at new settings area

---

GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd

add current pearl camera settings from NDXPEARL

---

G3HALLPR/G3HALLPR-IOC-01App/Makefile
G3HALLPR/G3HALLPR-IOC-01App/src/G3HALLPR-IOC-01Main.cpp
G3HALLPR/G3HALLPR-IOC-01App/src/Makefile
G3HALLPR/G3HALLPR-IOC-01App/src/build.mak
G3HALLPR/G3HALLPR-IOC-02App/Db/Makefile
G3HALLPR/G3HALLPR-IOC-02App/Makefile
G3HALLPR/G3HALLPR-IOC-02App/src/G3HALLPR-IOC-02Main.cpp
G3HALLPR/G3HALLPR-IOC-02App/src/Makefile
G3HALLPR/Makefile
G3HALLPR/configure/CONFIG
G3HALLPR/configure/CONFIG_SITE
G3HALLPR/configure/Makefile
G3HALLPR/configure/RELEASE
G3HALLPR/configure/RULES
G3HALLPR/configure/RULES.ioc
G3HALLPR/configure/RULES_DIRS
G3HALLPR/configure/RULES_TOP
G3HALLPR/iocBoot/Makefile
G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/Makefile
G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/config.xml
G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/st-common.cmd
G3HALLPR/iocBoot/iocG3HALLPR-IOC-01/st.cmd
G3HALLPR/iocBoot/iocG3HALLPR-IOC-02/Makefile
G3HALLPR/iocBoot/iocG3HALLPR-IOC-02/config.xml
G3HALLPR/iocBoot/iocG3HALLPR-IOC-02/st.cmd
Makefile

https://github.com/ISISComputingGroup/IBEX/issues/8400

Ticket8400 add ioc group3 hall probe

---

COMMON/HOST.xml
KSE4980/iocBoot/iocKSE4980-IOC-01/config.xml
LKSH336/iocBoot/iocLKSH336-IOC-01/config.xml
MEZFLIPR/iocBoot/iocMEZFLIPR-IOC-01/config.xml
PRLTHERM/iocBoot/iocPRLTHERM-IOC-01/config.xml
ZFMAGFLD/iocBoot/iocZFMAGFLD-IOC-01/config.xml

https://github.com/ISISComputingGroup/IBEX/issues/8280

Pulled host out to common macro

---

TLFW102C/TLFW102C-IOC-01App/src/build.mak

add missing library needed for static link
---

Fix missing mysql library

---

MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml

fix LKUP macro regex

---

MERCURY_ITC/iocBoot/iocMERCURY-IOC-01/config.xml

correct pattern

---

PSCTRL/PSCTRL-IOC-01App/src/build.mak

Add lib for static PSCTRL linking
---

Add static link library

---

MUONTPAR/iocBoot/iocMUONTPAR-IOC-01/st.cmd

See ISISComputingGroup/IBEX#8573
---

Use / to avoid trailing \ warning

---

PSCTRL/iocBoot/iocPSCTRL-IOC-01/st.cmd

Set initial connection delay for asyn
---

Set initial wait for conenction

---

GENICAM/iocBoot/iocGENICAM-IOC-01/devices/pearlcam_dbpfs.cmd

copy pearl cam settings from ndxpearl

---

TC/iocBoot/iocTC-IOC-01/st-common.cmd

https://github.com/ISISComputingGroup/IBEX/issues/8673

add configurable poll rate

---

HIFIMAGS/HIFIMAGS-IOC-01App/Db/hifimags_magnet.template
LKSH218/LKSH218-IOC-01App/Db/Lakeshore218Sensor.template
TLFW102C/iocBoot/iocTLFW102C-IOC-01/config.xml
ZFCNTRL/iocBoot/iocZFCNTRL-IOC-01/config.xml
ZFHIFI/iocBoot/iocZFHIFI-IOC-01/config.xml

https://github.com/ISISComputingGroup/IBEX/issues/6092
---

HIFI migration

---

DDSSTRES/DDSSTRES-IOC-01App/src/build.mak
DDSSTRES/iocBoot/iocDDSSTRES-IOC-01/st-common.cmd

https://github.com/ISISComputingGroup/IBEX/issues/8666

Ticket 8666 add state machine to dds

---

CAENMCA/configure/RELEASE
CAENMCA/iocBoot/iocCAENMCA-IOC-01/st-common.cmd
CAENMCA/iocBoot/iocCAENMCA-IOC-01/st-hexagon.cmd

Part of hexagon combine files
---
- [PV naming](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/conventions/PV-Naming.html).
- [Disable records](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/testing/Disable-records.html)
- [Record simulation](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/testing/Record-Simulation.html)
- [Finishing touches](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/creation/IOC-Finishing-Touches.html)

Hexagon combine files

---

CAENMCA/iocBoot/iocCAENMCA-IOC-01/st-common.cmd

---
- [PV naming](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/conventions/PV-Naming.html).
- [Disable records](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/testing/Disable-records.html)
- [Record simulation](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/testing/Record-Simulation.html)
- [Finishing touches](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/creation/IOC-Finishing-Touches.html)

Load dae sync

---

DELFTDCMAG/DELFTDCMAG-IOC-01App/Db/NSV1.db

The Ibex client gui display Echo_Coil RBV (TE:LARMOR:POLREVI2) in Amps. The setpoint (TE:LARMOR:POLREVI2:SP) should also be input in Amps. Output to the device is an integer current value in mA. A calc record has been interposed to convert user A to device mA.
[Ticket #8766]( https://github.com/orgs/ISISComputingGroup/projects/27/views/8?pane=issue&itemId=116118370&issue=ISISComputingGroup%7CIBEX%7C8766)
It is not feasible to create a test framework within the scope of this ticket. It has been agreed that a code review, followed by testing on the instrument will suffice.
---
- [PV naming](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/conventions/PV-Naming.html).
- [Disable records](https://isiscomputinggroup.github.io/ibex_developers_manual/iocs/testing/Disable-records.h …

Ticket8766 Larmor magnet ioc current
